/**
 * The model catalogue, as it stood when this file was generated.
 *
 * Generated by `scripts/catalogue.mjs` from models.dev - do not edit by hand. It exists so
 * the connection screen is fully populated on a first launch with no network; the live
 * fetch replaces it whenever one succeeds.
 *
 * TypeScript rather than JSON so no `resolveJsonModule` flag is needed and every bundler in
 * this repo treats it as ordinary source.
 */
import type { CatalogueProvider } from "./catalogueTypes.ts";

/** The day the upstream data was taken, for anyone wondering whether this has aged. */
export const SNAPSHOT_TAKEN_ON = "2026-08-23";

export const SNAPSHOT_PROVIDERS: readonly CatalogueProvider[] = [
  {
    "id": "anthropic",
    "name": "Anthropic",
    "env": [
      "ANTHROPIC_API_KEY"
    ],
    "doc": "https://docs.anthropic.com/en/docs/about-claude/models",
    "models": [
      {
        "id": "claude-opus-4-7",
        "name": "Claude Opus 4.7",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-opus-4-8",
        "name": "Claude Opus 4.8",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-sonnet-5",
        "name": "Claude Sonnet 5",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-sonnet-4-5-20250929",
        "name": "Claude Sonnet 4.5",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-opus-4-5",
        "name": "Claude Opus 4.5 (latest)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-sonnet-4-6",
        "name": "Claude Sonnet 4.6",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-haiku-4-5-20251001",
        "name": "Claude Haiku 4.5",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-sonnet-4-5",
        "name": "Claude Sonnet 4.5 (latest)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-opus-4-5-20251101",
        "name": "Claude Opus 4.5",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-fable-5",
        "name": "Claude Fable 5",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-haiku-4-5",
        "name": "Claude Haiku 4.5 (latest)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-opus-4-6",
        "name": "Claude Opus 4.6",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-opus-5",
        "name": "Claude Opus 5",
        "toolCall": true,
        "reasoning": true
      }
    ]
  },
  {
    "id": "openai",
    "name": "OpenAI",
    "env": [
      "OPENAI_API_KEY"
    ],
    "doc": "https://platform.openai.com/docs/models",
    "models": [
      {
        "id": "gpt-4o",
        "name": "GPT-4o",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "gpt-image-1.5",
        "name": "gpt-image-1.5",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "gpt-5.3-chat-latest",
        "name": "GPT-5.3 Chat (latest)",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "gpt-5-nano",
        "name": "GPT-5 Nano",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-4o-mini",
        "name": "GPT-4o mini",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "gpt-3.5-turbo",
        "name": "GPT-3.5-turbo",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "o1-pro",
        "name": "o1-pro",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5.5-pro",
        "name": "GPT-5.5 Pro",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-4-turbo",
        "name": "GPT-4 Turbo",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "gpt-image-1-mini",
        "name": "gpt-image-1-mini",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "gpt-4",
        "name": "GPT-4",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "gpt-5.6-sol",
        "name": "GPT-5.6 Sol",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "o3-pro",
        "name": "o3-pro",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5.4-pro",
        "name": "GPT-5.4 Pro",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5",
        "name": "GPT-5",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5.6",
        "name": "GPT-5.6",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5-mini",
        "name": "GPT-5 Mini",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5.6-luna",
        "name": "GPT-5.6 Luna",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "text-embedding-ada-002",
        "name": "text-embedding-ada-002",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "gpt-5.3-codex",
        "name": "GPT-5.3 Codex",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5.3-codex-spark",
        "name": "GPT-5.3 Codex Spark",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-4.1-nano",
        "name": "GPT-4.1 nano",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "o1",
        "name": "o1",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5.2",
        "name": "GPT-5.2",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-image-1",
        "name": "gpt-image-1",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "gpt-realtime-2.1",
        "name": "GPT-Realtime-2.1",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5.4-mini",
        "name": "GPT-5.4 mini",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-4o-2024-05-13",
        "name": "GPT-4o (2024-05-13)",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "o3",
        "name": "o3",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "chatgpt-image-latest",
        "name": "chatgpt-image-latest",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "text-embedding-3-small",
        "name": "text-embedding-3-small",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "gpt-5-pro",
        "name": "GPT-5 Pro",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5.5",
        "name": "GPT-5.5",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-4.1",
        "name": "GPT-4.1",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "gpt-4o-2024-08-06",
        "name": "GPT-4o (2024-08-06)",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "gpt-5.6-terra",
        "name": "GPT-5.6 Terra",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "o4-mini",
        "name": "o4-mini",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5.4",
        "name": "GPT-5.4",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "o3-mini",
        "name": "o3-mini",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-4o-2024-11-20",
        "name": "GPT-4o (2024-11-20)",
        "toolCall": true,
        "reasoning": false
      }
    ]
  },
  {
    "id": "google",
    "name": "Google",
    "env": [
      "GOOGLE_API_KEY",
      "GOOGLE_GENERATIVE_AI_API_KEY",
      "GEMINI_API_KEY"
    ],
    "doc": "https://ai.google.dev/gemini-api/docs/models",
    "models": [
      {
        "id": "gemini-3.1-flash-tts-preview",
        "name": "Gemini 3.1 Flash TTS Preview",
        "toolCall": false,
        "reasoning": true
      },
      {
        "id": "gemma-4-26b-a4b-it",
        "name": "Gemma 4 26B A4B IT",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gemini-3-pro-image",
        "name": "Nano Banana Pro",
        "toolCall": false,
        "reasoning": true
      },
      {
        "id": "gemini-3-pro-image-preview",
        "name": "Nano Banana Pro",
        "toolCall": false,
        "reasoning": true
      },
      {
        "id": "gemini-flash-lite-latest",
        "name": "Gemini Flash-Lite Latest",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gemini-3.5-flash-lite",
        "name": "Gemini 3.5 Flash Lite",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gemini-3.1-flash-lite-image",
        "name": "Nano Banana 2 Lite",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gemini-3.1-pro-preview",
        "name": "Gemini 3.1 Pro Preview",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gemini-3.1-pro-preview-customtools",
        "name": "Gemini 3.1 Pro Preview Custom Tools",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "deep-research-preview-04-2026",
        "name": "Deep Research Preview (Apr-21-2026)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gemini-2.5-flash-lite",
        "name": "Gemini 2.5 Flash-Lite",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gemini-robotics-er-1.6-preview",
        "name": "Gemini Robotics-ER 1.6 Preview",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gemma-4-31b-it",
        "name": "Gemma 4 31B IT",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gemini-2.5-computer-use-preview-10-2025",
        "name": "Gemini 2.5 Computer Use Preview 10-2025",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "lyria-3-clip-preview",
        "name": "Lyria 3 Clip Preview",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "veo-3.1-fast-generate-preview",
        "name": "Veo 3.1 fast",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "gemini-embedding-001",
        "name": "Gemini Embedding 001",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "gemini-2.5-pro-preview-tts",
        "name": "Gemini 2.5 Pro Preview TTS",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "gemini-flash-latest",
        "name": "Gemini Flash Latest",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gemini-3.5-flash",
        "name": "Gemini 3.5 Flash",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gemini-3.5-live-translate-preview",
        "name": "Gemini 3.5 Live Translate Preview",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "veo-3.1-lite-generate-preview",
        "name": "Veo 3.1 lite",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "gemini-omni-flash-preview",
        "name": "Gemini Omni Flash Preview",
        "toolCall": false,
        "reasoning": true
      },
      {
        "id": "gemini-3.1-flash-lite",
        "name": "Gemini 3.1 Flash Lite",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gemini-2.5-flash",
        "name": "Gemini 2.5 Flash",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gemini-2.5-flash-preview-tts",
        "name": "Gemini 2.5 Flash Preview TTS",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "veo-3.1-generate-preview",
        "name": "Veo 3.1",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "gemini-embedding-2",
        "name": "Gemini Embedding 2",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "gemini-3.6-flash",
        "name": "Gemini 3.6 Flash",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gemini-3.1-flash-image",
        "name": "Nano Banana 2",
        "toolCall": false,
        "reasoning": true
      },
      {
        "id": "gemini-3.1-flash-image-preview",
        "name": "Nano Banana 2",
        "toolCall": false,
        "reasoning": true
      },
      {
        "id": "lyria-3-pro-preview",
        "name": "Lyria 3 Pro Preview",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "gemini-3.1-flash-lite-preview",
        "name": "Gemini 3.1 Flash Lite Preview",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gemini-3-flash-preview",
        "name": "Gemini 3 Flash Preview",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gemini-2.5-flash-image",
        "name": "Nano Banana",
        "toolCall": false,
        "reasoning": true
      },
      {
        "id": "gemini-2.5-pro",
        "name": "Gemini 2.5 Pro",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "deep-research-max-preview-04-2026",
        "name": "Deep Research Max Preview (Apr-21-2026)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gemini-3.1-flash-live-preview",
        "name": "Gemini 3.1 Flash Live Preview",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gemini-3.7-flash",
        "name": "Gemini 3.7 Flash",
        "toolCall": true,
        "reasoning": true
      }
    ]
  },
  {
    "id": "openrouter",
    "name": "OpenRouter",
    "env": [
      "OPENROUTER_API_KEY"
    ],
    "doc": "https://openrouter.ai/models",
    "models": [
      {
        "id": "tencent/hy-mt2-30b-a3b",
        "name": "Hy-MT2-30B-A3B",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "tencent/hy-mt2-1.8b",
        "name": "Hy-MT2-1.8B",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "tencent/hy3-preview",
        "name": "Hy3 preview",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "tencent/hunyuan-a13b-instruct",
        "name": "Hunyuan A13B Instruct",
        "toolCall": false,
        "reasoning": true
      },
      {
        "id": "tencent/hy3",
        "name": "Hy3",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "tencent/hy-mt2-7b",
        "name": "Hy-MT2-7B",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "~anthropic/claude-haiku-latest",
        "name": "Anthropic Claude Haiku Latest",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "~anthropic/claude-opus-latest",
        "name": "Claude Opus Latest",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "~anthropic/claude-sonnet-latest",
        "name": "Anthropic Claude Sonnet Latest",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "~anthropic/claude-fable-latest",
        "name": "Claude Fable Latest",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "~x-ai/grok-latest",
        "name": "Grok Latest",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "nvidia/nemotron-3-super-120b-a12b:free",
        "name": "Nemotron 3 Super (free)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "nvidia/nemotron-3-nano-30b-a3b",
        "name": "Nemotron 3 Nano 30B A3B",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "nvidia/nemotron-3-super-120b-a12b",
        "name": "Nemotron 3 Super 120B A12B",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "nvidia/nemotron-3.5-lightning",
        "name": "Nemotron 3.5 Lightning 30B A3B",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "nvidia/nemotron-nano-12b-v2-vl:free",
        "name": "Nemotron Nano 12B 2 VL (free)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "nvidia/nemotron-3-ultra-550b-a55b",
        "name": "Nemotron 3 Ultra 550B A55B",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "nvidia/nemotron-3.5-lightning:free",
        "name": "Nemotron 3.5 Lightning (free)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
        "name": "Nemotron 3 Nano Omni (free)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "nvidia/nemotron-3.5-content-safety:free",
        "name": "Nemotron 3.5 Content Safety (free)",
        "toolCall": false,
        "reasoning": true
      },
      {
        "id": "nvidia/nemotron-3-ultra-550b-a55b:free",
        "name": "Nemotron 3 Ultra (free)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "nvidia/nemotron-3-nano-30b-a3b:free",
        "name": "Nemotron 3 Nano 30B A3B (free)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "nvidia/nemotron-nano-9b-v2:free",
        "name": "Nemotron Nano 9B V2 (free)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "~openai/gpt-latest",
        "name": "OpenAI GPT Latest",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "~openai/gpt-mini-latest",
        "name": "OpenAI GPT Mini Latest",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "aion-labs/aion-3.0",
        "name": "Aion-3.0",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "aion-labs/aion-rp-llama-3.1-8b",
        "name": "Aion-RP 1.0 (8B)",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "aion-labs/aion-2.0",
        "name": "Aion-2.0",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "aion-labs/aion-3.0-mini",
        "name": "Aion-3.0-Mini",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "undi95/remm-slerp-l2-13b",
        "name": "ReMM SLERP 13B",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "microsoft/wizardlm-2-8x22b",
        "name": "WizardLM-2 8x22B",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "microsoft/phi-4",
        "name": "Phi 4",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "z-ai/glm-4.6",
        "name": "GLM-4.6",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "z-ai/glm-5v-turbo",
        "name": "GLM-5V-Turbo",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "z-ai/glm-4.7",
        "name": "GLM-4.7",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "z-ai/glm-4.5v",
        "name": "GLM-4.5V",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "z-ai/glm-5.2:free",
        "name": "GLM 5.2 (free)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "z-ai/glm-5",
        "name": "GLM-5",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "z-ai/glm-5-turbo",
        "name": "GLM-5-Turbo",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "z-ai/glm-5.3",
        "name": "GLM-5.3",
        "toolCall": true,
        "reasoning": true
      }
    ]
  },
  {
    "id": "groq",
    "name": "Groq",
    "env": [
      "GROQ_API_KEY"
    ],
    "doc": "https://console.groq.com/docs/models",
    "models": [
      {
        "id": "whisper-large-v3",
        "name": "Whisper",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "llama-3.3-70b-versatile",
        "name": "Llama 3.3 70B",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "allam-2-7b",
        "name": "ALLaM-2-7b",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "llama-3.1-8b-instant",
        "name": "Llama 3.1 8B",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "whisper-large-v3-turbo",
        "name": "Whisper Large V3 Turbo",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "openai/gpt-oss-120b",
        "name": "GPT OSS 120B",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "openai/gpt-oss-safeguard-20b",
        "name": "Safety GPT OSS 20B",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "openai/gpt-oss-20b",
        "name": "GPT OSS 20B",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "qwen/qwen3.6-27b",
        "name": "Qwen3.6 27B",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "meta-llama/llama-prompt-guard-2-86m",
        "name": "Prompt Guard 2 86M",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "meta-llama/llama-prompt-guard-2-22m",
        "name": "Llama Prompt Guard 2 22M",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "groq/compound-mini",
        "name": "Compound Mini",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "groq/compound",
        "name": "Compound",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "canopylabs/orpheus-arabic-saudi",
        "name": "Canopy Labs Orpheus Arabic Saudi",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "canopylabs/orpheus-v1-english",
        "name": "Canopy Labs Orpheus V1 English",
        "toolCall": false,
        "reasoning": false
      }
    ]
  },
  {
    "id": "mistral",
    "name": "Mistral",
    "env": [
      "MISTRAL_API_KEY"
    ],
    "doc": "https://docs.mistral.ai/getting-started/models/",
    "models": [
      {
        "id": "mistral-medium-2508",
        "name": "Mistral Medium 3.1",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "mistral-small-latest",
        "name": "Mistral Small (latest)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "devstral-medium-2507",
        "name": "Devstral Medium",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "open-mixtral-8x7b",
        "name": "Mixtral 8x7B",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "mistral-large-2411",
        "name": "Mistral Large 2.1",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "mistral-nemo",
        "name": "Mistral Nemo",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "devstral-latest",
        "name": "Devstral 2",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "mistral-large-latest",
        "name": "Mistral Large (latest)",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "devstral-small-2507",
        "name": "Devstral Small",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "devstral-2512",
        "name": "Devstral 2",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "labs-devstral-small-2512",
        "name": "Devstral Small 2",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "open-mistral-nemo",
        "name": "Open Mistral Nemo",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "mistral-small-2603",
        "name": "Mistral Small 4",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "magistral-small",
        "name": "Magistral Small",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "voxtral-mini-latest",
        "name": "Voxtral Mini (latest)",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "mistral-small-2506",
        "name": "Mistral Small 3.2",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "pixtral-large-latest",
        "name": "Pixtral Large (latest)",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "mistral-large-2512",
        "name": "Mistral Large 3",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "ministral-3b-latest",
        "name": "Ministral 3B (latest)",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "mistral-medium-2604",
        "name": "Mistral Medium 3.5",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "devstral-small-2505",
        "name": "Devstral Small 2505",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "ministral-8b-latest",
        "name": "Ministral 8B (latest)",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "mistral-medium-2505",
        "name": "Mistral Medium 3",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "devstral-medium-latest",
        "name": "Devstral 2 (latest)",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "open-mistral-7b",
        "name": "Mistral 7B",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "voxtral-mini-tts-latest",
        "name": "Voxtral Mini TTS (latest)",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "pixtral-12b",
        "name": "Pixtral 12B",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "voxtral-small-latest",
        "name": "Voxtral Small (latest)",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "codestral-latest",
        "name": "Codestral (latest)",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "open-mixtral-8x22b",
        "name": "Mixtral 8x22B",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "magistral-medium-latest",
        "name": "Magistral Medium (latest)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "mistral-embed",
        "name": "Mistral Embed",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "mistral-medium-latest",
        "name": "Mistral Medium (latest)",
        "toolCall": true,
        "reasoning": true
      }
    ]
  },
  {
    "id": "deepseek",
    "name": "DeepSeek",
    "env": [
      "DEEPSEEK_API_KEY"
    ],
    "doc": "https://api-docs.deepseek.com/quick_start/pricing",
    "models": [
      {
        "id": "deepseek-v4-flash",
        "name": "DeepSeek V4 Flash",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "deepseek-v4-pro",
        "name": "DeepSeek V4 Pro",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "deepseek-chat",
        "name": "DeepSeek Chat",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "deepseek-reasoner",
        "name": "DeepSeek Reasoner",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "deepseek-v4-flash-vision-exp",
        "name": "DeepSeek V4 Flash Vision Exp",
        "toolCall": true,
        "reasoning": true
      }
    ]
  },
  {
    "id": "xai",
    "name": "xAI",
    "env": [
      "XAI_API_KEY"
    ],
    "doc": "https://docs.x.ai/docs/models",
    "models": [
      {
        "id": "grok-imagine-video",
        "name": "Grok Imagine Video",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "grok-4.6",
        "name": "Grok 4.6",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "grok-4.5",
        "name": "Grok 4.5",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "grok-4.20-0309-non-reasoning",
        "name": "Grok 4.20 (Non-Reasoning)",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "grok-imagine-video-1.5",
        "name": "Grok Imagine Video 1.5",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "grok-imagine-image-quality",
        "name": "Grok Imagine Image Quality",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "grok-4.20-0309-reasoning",
        "name": "Grok 4.20 (Reasoning)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "grok-4.20-multi-agent-0309",
        "name": "Grok 4.20 Multi-Agent",
        "toolCall": false,
        "reasoning": true
      },
      {
        "id": "grok-imagine-image-2.0",
        "name": "Grok Imagine Image 2.0",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "grok-imagine-image",
        "name": "Grok Imagine Image",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "grok-build-0.1",
        "name": "Grok Build 0.1",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "grok-4.3",
        "name": "Grok 4.3",
        "toolCall": true,
        "reasoning": true
      }
    ]
  },
  {
    "id": "fireworks-ai",
    "name": "Fireworks AI",
    "env": [
      "FIREWORKS_API_KEY"
    ],
    "doc": "https://fireworks.ai/docs/",
    "models": [
      {
        "id": "accounts/fireworks/routers/kimi-k2p6-fast",
        "name": "Kimi K2.6 Fast",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "accounts/fireworks/routers/kimi-k3-fast",
        "name": "Kimi K3 Fast",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "accounts/fireworks/routers/glm-5p2-fast",
        "name": "GLM 5.2 Fast",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "accounts/fireworks/routers/kimi-k2p7-code-fast",
        "name": "Kimi K2.7 Code Fast",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "accounts/fireworks/routers/kimi-k2p6-turbo",
        "name": "Kimi K2.6 Turbo",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "accounts/fireworks/models/kimi-k3",
        "name": "Kimi K3",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "accounts/fireworks/models/deepseek-v4-flash",
        "name": "DeepSeek V4 Flash",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "accounts/fireworks/models/qwen3p8-max",
        "name": "Qwen3.8 Max",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "accounts/fireworks/models/nemotron-3-ultra-nvfp4",
        "name": "Nemotron 3 Ultra 550B A55B",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "accounts/fireworks/models/deepseek-v4-pro-0813",
        "name": "DeepSeek V4 Pro 0813",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "accounts/fireworks/models/deepseek-v4-pro",
        "name": "DeepSeek V4 Pro",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "accounts/fireworks/models/nemotron-lightning-3p5-30b-a3b",
        "name": "Nemotron 3.5 Lightning 30B A3B",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "accounts/fireworks/models/minimax-m3",
        "name": "MiniMax-M3",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "accounts/fireworks/models/muse-glimmer-30b",
        "name": "Muse Glimmer 30B",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "accounts/fireworks/models/gpt-oss-120b",
        "name": "GPT OSS 120B",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "accounts/fireworks/models/kimi-k2p7-code",
        "name": "Kimi K2.7 Code",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "accounts/fireworks/models/inkling",
        "name": "Inkling",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "accounts/fireworks/models/glm-5p2",
        "name": "GLM 5.2",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "accounts/fireworks/models/qwen3p7-plus",
        "name": "Qwen 3.7 Plus",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "accounts/fireworks/models/kimi-k2p6",
        "name": "Kimi K2.6",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "accounts/fireworks/models/deepseek-v4-flash-0731",
        "name": "DeepSeek V4 Flash 0731",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "accounts/fireworks/models/gpt-oss-20b",
        "name": "GPT OSS 20B",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "accounts/fireworks/models/minimax-m2p7",
        "name": "MiniMax-M2.7",
        "toolCall": true,
        "reasoning": true
      }
    ]
  },
  {
    "id": "cerebras",
    "name": "Cerebras",
    "env": [
      "CEREBRAS_API_KEY"
    ],
    "doc": "https://inference-docs.cerebras.ai/models/overview",
    "models": [
      {
        "id": "gpt-oss-120b",
        "name": "GPT OSS 120B",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gemma-4-31b",
        "name": "Gemma 4 31B IT",
        "toolCall": true,
        "reasoning": true
      }
    ]
  },
  {
    "id": "azure",
    "name": "Azure",
    "env": [
      "AZURE_RESOURCE_NAME",
      "AZURE_API_KEY"
    ],
    "doc": "https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models",
    "models": [
      {
        "id": "phi-4-reasoning-plus",
        "name": "Phi-4-reasoning-plus",
        "toolCall": false,
        "reasoning": true
      },
      {
        "id": "deepseek-v3.2-speciale",
        "name": "DeepSeek-V3.2-Speciale",
        "toolCall": false,
        "reasoning": true
      },
      {
        "id": "claude-opus-4-7",
        "name": "Claude Opus 4.7",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-4o",
        "name": "GPT-4o",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "gpt-image-1.5",
        "name": "GPT-Image-1.5",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "claude-mythos-5",
        "name": "Claude Mythos 5",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "kimi-k2.7-code",
        "name": "Kimi K2.7 Code",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "deepseek-r1",
        "name": "DeepSeek-R1",
        "toolCall": false,
        "reasoning": true
      },
      {
        "id": "codestral-2501",
        "name": "Codestral 25.01",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "gpt-5-nano",
        "name": "GPT-5 Nano",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-4o-mini",
        "name": "GPT-4o mini",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "gpt-4-turbo",
        "name": "GPT-4 Turbo",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "deepseek-v4-flash",
        "name": "DeepSeek-V4-Flash",
        "toolCall": false,
        "reasoning": true
      },
      {
        "id": "phi-4-mini",
        "name": "Phi-4-mini",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "claude-opus-4-8",
        "name": "Claude Opus 4.8",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-3.5-turbo-instruct",
        "name": "GPT-3.5 Turbo Instruct",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "gpt-5.6-sol",
        "name": "GPT-5.6 Sol",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "llama-3.3-70b-instruct",
        "name": "Llama-3.3-70B-Instruct",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "gpt-5.4-pro",
        "name": "GPT-5.4 Pro",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5",
        "name": "GPT-5",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-opus-4-1",
        "name": "Claude Opus 4.1",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "cohere-embed-v-4-0",
        "name": "Embed v4",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "deepseek-v4-pro",
        "name": "DeepSeek-V4-Pro",
        "toolCall": false,
        "reasoning": true
      },
      {
        "id": "claude-sonnet-5",
        "name": "Claude Sonnet 5",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-3.5-turbo-1106",
        "name": "GPT-3.5 Turbo 1106",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "deepseek-v3.2",
        "name": "DeepSeek-V3.2",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5.1-codex-mini",
        "name": "GPT-5.1 Codex Mini",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5-codex",
        "name": "GPT-5-Codex",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "grok-4-1-fast-reasoning",
        "name": "Grok 4.1 Fast (Reasoning)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5-mini",
        "name": "GPT-5 Mini",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "codex-mini",
        "name": "Codex Mini",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5.6-luna",
        "name": "GPT-5.6 Luna",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "text-embedding-ada-002",
        "name": "text-embedding-ada-002",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "ministral-3b",
        "name": "Ministral 3B",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "gpt-5.3-codex",
        "name": "GPT-5.3 Codex",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-4.1-nano",
        "name": "GPT-4.1 nano",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "o1",
        "name": "o1",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5.2",
        "name": "GPT-5.2",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-image-1",
        "name": "GPT-Image-1",
        "toolCall": false,
        "reasoning": false
      },
      {
        "id": "claude-opus-4-5",
        "name": "Claude Opus 4.5",
        "toolCall": true,
        "reasoning": true
      }
    ]
  },
  {
    "id": "amazon-bedrock",
    "name": "Amazon Bedrock",
    "env": [
      "AWS_ACCESS_KEY_ID",
      "AWS_SECRET_ACCESS_KEY",
      "AWS_REGION",
      "AWS_BEARER_TOKEN_BEDROCK"
    ],
    "doc": "https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html",
    "models": [
      {
        "id": "us.anthropic.claude-fable-5",
        "name": "Claude Fable 5 (US)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "qwen.qwen3-coder-480b-a35b-v1:0",
        "name": "Qwen3 Coder 480B A35B Instruct",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "jp.anthropic.claude-sonnet-5",
        "name": "Claude Sonnet 5 (JP)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "jp.anthropic.claude-opus-4-7",
        "name": "Claude Opus 4.7 (JP)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "mistral.pixtral-large-2502-v1:0",
        "name": "Pixtral Large (25.02)",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "jp.anthropic.claude-sonnet-4-5-20250929-v1:0",
        "name": "Claude Sonnet 4.5 (JP)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "au.anthropic.claude-sonnet-5",
        "name": "Claude Sonnet 5 (AU)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "global.anthropic.claude-sonnet-4-6",
        "name": "Claude Sonnet 4.6 (Global)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "qwen.qwen3-235b-a22b-2507-v1:0",
        "name": "Qwen3 235B A22B 2507",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "au.anthropic.claude-sonnet-4-6",
        "name": "AU Anthropic Claude Sonnet 4.6",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "global.openai.gpt-5.6-sol",
        "name": "GPT-5.6 Sol (Global)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "jp.anthropic.claude-sonnet-4-6",
        "name": "Claude Sonnet 4.6 (JP)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "deepseek.v3.2",
        "name": "DeepSeek-V3.2",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "anthropic.claude-sonnet-4-5-20250929-v1:0",
        "name": "Claude Sonnet 4.5",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "mistral.ministral-3-3b-instruct",
        "name": "Ministral 3 3B",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "anthropic.claude-haiku-4-5-20251001-v1:0",
        "name": "Claude Haiku 4.5",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "global.anthropic.claude-sonnet-5",
        "name": "Claude Sonnet 5 (Global)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "eu.anthropic.claude-opus-5",
        "name": "Claude Opus 5 (EU)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "mistral.mistral-large-3-675b-instruct",
        "name": "Mistral Large 3",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "openai.gpt-5.6-terra",
        "name": "GPT-5.6 Terra",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "minimax.minimax-m2",
        "name": "MiniMax M2",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "us.deepseek.r1-v1:0",
        "name": "DeepSeek-R1 (US)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "mistral.voxtral-small-24b-2507",
        "name": "Voxtral Small 24B 2507",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "qwen.qwen3-coder-next",
        "name": "Qwen3 Coder Next",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "openai.gpt-oss-safeguard-120b",
        "name": "GPT OSS Safeguard 120B",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "us.anthropic.claude-opus-4-1-20250805-v1:0",
        "name": "Claude Opus 4.1 (US)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "us.meta.llama4-maverick-17b-instruct-v1:0",
        "name": "Llama 4 Maverick 17B Instruct (US)",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "eu.anthropic.claude-fable-5",
        "name": "Claude Fable 5 (EU)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "jp.anthropic.claude-haiku-4-5-20251001-v1:0",
        "name": "Claude Haiku 4.5 (JP)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "au.anthropic.claude-opus-4-8",
        "name": "Claude Opus 4.8 (AU)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "global.anthropic.claude-sonnet-4-5-20250929-v1:0",
        "name": "Claude Sonnet 4.5 (Global)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "eu.anthropic.claude-haiku-4-5-20251001-v1:0",
        "name": "Claude Haiku 4.5 (EU)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "moonshot.kimi-k2-thinking",
        "name": "Kimi K2 Thinking",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "au.anthropic.claude-sonnet-4-5-20250929-v1:0",
        "name": "Claude Sonnet 4.5 (AU)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "meta.llama4-maverick-17b-instruct-v1:0",
        "name": "Llama 4 Maverick 17B Instruct",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "us.anthropic.claude-opus-5",
        "name": "Claude Opus 5 (US)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "amazon.nova-pro-v1:0",
        "name": "Nova Pro",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "qwen.qwen3-vl-235b-a22b",
        "name": "Qwen/Qwen3-VL-235B-A22B-Instruct",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "openai.gpt-oss-120b",
        "name": "gpt-oss-120b",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "openai.gpt-5.5",
        "name": "GPT-5.5",
        "toolCall": true,
        "reasoning": true
      }
    ]
  },
  {
    "id": "github-copilot",
    "name": "GitHub Copilot",
    "env": [
      "GITHUB_TOKEN"
    ],
    "doc": "https://docs.github.com/en/copilot",
    "models": [
      {
        "id": "kimi-k2.7-code",
        "name": "Kimi K2.7 Code",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-opus-4.8",
        "name": "Claude Opus 4.8",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "kimi-k3",
        "name": "Kimi K3",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "mai-code-1-flash-picker",
        "name": "MAI-Code-1-Flash",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5.6-sol",
        "name": "GPT-5.6 Sol",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "grok-4.6",
        "name": "Grok 4.6",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-sonnet-4.6",
        "name": "Claude Sonnet 4.6",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gemini-3.1-pro-preview",
        "name": "Gemini 3.1 Pro Preview",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "grok-4.5",
        "name": "Grok 4.5",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-sonnet-5",
        "name": "Claude Sonnet 5",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-haiku-4.5",
        "name": "Claude Haiku 4.5 (latest)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5-mini",
        "name": "GPT-5 Mini",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5.6-luna",
        "name": "GPT-5.6 Luna",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-opus-4.7",
        "name": "Claude Opus 4.7",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-opus-4.5",
        "name": "Claude Opus 4.5 (latest)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5.3-codex",
        "name": "GPT-5.3 Codex",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-sonnet-4",
        "name": "Claude Sonnet 4 (latest)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5.2",
        "name": "GPT-5.2",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gemini-3.5-flash",
        "name": "Gemini 3.5 Flash",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5.4-mini",
        "name": "GPT-5.4 mini",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5.5",
        "name": "GPT-5.5",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-opus-4.6",
        "name": "Claude Opus 4.6",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5.2-codex",
        "name": "GPT-5.2 Codex",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-4.1",
        "name": "GPT-4.1",
        "toolCall": true,
        "reasoning": false
      },
      {
        "id": "gemini-3.6-flash",
        "name": "Gemini 3.6 Flash",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5.6-terra",
        "name": "GPT-5.6 Terra",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5.4",
        "name": "GPT-5.4",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-sonnet-4.5",
        "name": "Claude Sonnet 4.5 (latest)",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-fable-5",
        "name": "Claude Fable 5",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "claude-opus-5",
        "name": "Claude Opus 5",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "mai-code-1.1-flash",
        "name": "MAI-Code-1.1-Flash",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gemini-3.7-flash",
        "name": "Gemini 3.7 Flash",
        "toolCall": true,
        "reasoning": true
      },
      {
        "id": "gpt-5.4-nano",
        "name": "GPT-5.4 nano",
        "toolCall": true,
        "reasoning": true
      }
    ]
  }
];
