/**
 * Which models exist, and which of them this machine can reach.
 *
 * The provider list used to be a hardcoded map of four names in the main process, which
 * meant the model dropdown showed models the user's key could not reach and hid ones it
 * could. This replaces it with the published catalogue - and, more importantly, with the
 * idea that the list is *data* rather than a build-time decision.
 *
 * Two sources, in that order:
 *
 * - **The snapshot**, generated by `scripts/catalogue.mjs` and shipped in the binary, so a
 *   first launch with no network has a fully populated connection screen rather than an
 *   empty one that looks broken.
 * - **The live fetch**, which replaces it whenever one succeeds. Never required.
 *
 * This module is pure: parsing and merging only. Fetching and caching belong to the shell.
 */
import { SNAPSHOT_PROVIDERS, SNAPSHOT_TAKEN_ON } from "./catalogueSnapshot.ts";
import type { CatalogueModel, CatalogueProvider } from "./catalogueTypes.ts";
import type { ModelTraits } from "./types.ts";

export type { CatalogueModel, CatalogueProvider } from "./catalogueTypes.ts";

export { SNAPSHOT_TAKEN_ON };

/** What ships in the binary. */
export const BUNDLED_CATALOGUE: readonly CatalogueProvider[] = SNAPSHOT_PROVIDERS;

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null;

function costMicros(raw: unknown): number | null {
  if (typeof raw !== "number" || !Number.isFinite(raw) || raw < 0) return null;
  const micros = Math.round(raw * 1_000_000);
  return Number.isSafeInteger(micros) ? micros : null;
}

/**
 * A model's context size in tokens, or null when absent or implausible.
 *
 * Nothing reads fewer than a thousand tokens or more than a billion; outside that is a typo
 * upstream, and a wrong size is worse than none - it decides when a conversation compacts.
 */
function contextTokens(raw: unknown): number | null {
  if (typeof raw !== "number" || !Number.isSafeInteger(raw)) return null;
  return raw >= 1_000 && raw <= 1_000_000_000 ? raw : null;
}

/** What a model with no published size is assumed to read: small enough to be safe. */
export const DEFAULT_CONTEXT_WINDOW = 128_000;

function modelsFrom(raw: unknown): CatalogueModel[] {
  if (!isRecord(raw)) return [];

  const models: CatalogueModel[] = [];

  for (const entry of Object.values(raw)) {
    if (!isRecord(entry)) continue;

    const id = entry["id"];
    if (typeof id !== "string" || id.length === 0) continue;

    const name = entry["name"];
    const cost = isRecord(entry["cost"]) ? entry["cost"] : {};
    const limit = isRecord(entry["limit"]) ? entry["limit"] : {};
    const modalities = isRecord(entry["modalities"]) ? entry["modalities"] : {};
    // Optional facts appear only when upstream published them, so an entry without them reads
    // exactly as it always did.
    const maxOutput = contextTokens(limit["output"]);
    const effortLevels = effortLevelsOf(entry["reasoning_options"]);
    const releaseDate = typeof entry["release_date"] === "string" && /^\d{4}-\d{2}-\d{2}$/.test(entry["release_date"]) ? entry["release_date"] : null;
    const status = typeof entry["status"] === "string" && entry["status"].length > 0 ? entry["status"] : null;
    const family = typeof entry["family"] === "string" && entry["family"].length > 0 ? entry["family"] : null;
    const inputs = stringList(modalities["input"]);
    const outputs = stringList(modalities["output"]);
    models.push({
      id,
      name: typeof name === "string" && name.length > 0 ? name : id,
      toolCall: entry["tool_call"] === true,
      reasoning: entry["reasoning"] === true,
      inputCostMicrosPerMillion: costMicros(cost["input"]),
      outputCostMicrosPerMillion: costMicros(cost["output"]),
      cacheReadCostMicrosPerMillion: costMicros(cost["cache_read"]),
      cacheWriteCostMicrosPerMillion: costMicros(cost["cache_write"]),
      contextWindow: contextTokens(limit["context"]),
      ...(maxOutput === null ? {} : { maxOutput }),
      ...(effortLevels === null ? {} : { effortLevels }),
      ...(releaseDate === null ? {} : { releaseDate }),
      ...(status === null ? {} : { status }),
      ...(family === null ? {} : { family }),
      ...(inputs === null ? {} : { inputs }),
      ...(outputs === null ? {} : { outputs }),
    });
  }

  return models;
}

function stringList(raw: unknown): string[] | null {
  if (!Array.isArray(raw)) return null;
  const list = raw.filter((one): one is string => typeof one === "string" && one.length > 0 && one.length < 40);
  return list.length > 0 ? list : null;
}

/** The effort levels from models.dev's `reasoning_options`, or null when it lists none. */
function effortLevelsOf(raw: unknown): string[] | null {
  if (!Array.isArray(raw)) return null;
  for (const option of raw) {
    if (isRecord(option) && option["type"] === "effort") return stringList(option["values"]);
  }
  return null;
}

/**
 * Read the published catalogue into our own shape.
 *
 * Every field is checked. This is arbitrary JSON from the network reaching a list the user
 * will pick from, and the shape upstream publishes is not a promise anybody made us.
 */
export function parseCatalogue(raw: unknown): CatalogueProvider[] {
  if (!isRecord(raw)) return [];

  const providers: CatalogueProvider[] = [];

  for (const [key, entry] of Object.entries(raw)) {
    if (!isRecord(entry)) continue;

    const models = modelsFrom(entry["models"]);
    // A provider with no models is a row that can only disappoint.
    if (models.length === 0) continue;

    const id = entry["id"];
    const name = entry["name"];
    const env = entry["env"];
    const doc = entry["doc"];

    providers.push({
      id: typeof id === "string" && id.length > 0 ? id : key,
      name: typeof name === "string" && name.length > 0 ? name : key,
      env: Array.isArray(env) ? env.filter((one): one is string => typeof one === "string") : [],
      doc: typeof doc === "string" ? doc : null,
      models,
    });
  }

  return providers.sort((a, b) => a.name.localeCompare(b.name));
}

/** The context size the catalogue gives a provider's model, or null when it gives none. */
export function contextWindowOf(
  catalogue: readonly CatalogueProvider[],
  providerId: string,
  modelId: string,
): number | null {
  const model = catalogue.find((provider) => provider.id === providerId)?.models.find((one) => one.id === modelId);
  return model?.contextWindow ?? null;
}

/**
 * The live catalogue where there is one, the snapshot where there is not.
 *
 * A live answer replaces a provider wholesale rather than being merged into it field by
 * field: a model that upstream has removed should disappear, and a merge would keep it
 * forever.
 */
export function mergeCatalogue(
  bundled: readonly CatalogueProvider[],
  live: readonly CatalogueProvider[],
): CatalogueProvider[] {
  if (live.length === 0) return [...bundled];

  const byId = new Map(bundled.map((provider) => [provider.id, provider]));
  for (const provider of live) byId.set(provider.id, provider);

  return [...byId.values()].sort((a, b) => a.name.localeCompare(b.name));
}

export function providerIn(
  catalogue: readonly CatalogueProvider[],
  id: string,
): CatalogueProvider | undefined {
  return catalogue.find((provider) => provider.id === id);
}

/**
 * Providers and models matching a query.
 *
 * Matches the provider's name as well as the model's, because "anthropic" is a perfectly
 * reasonable thing to type when looking for Claude.
 */
export function searchCatalogue(
  catalogue: readonly CatalogueProvider[],
  query: string,
): CatalogueProvider[] {
  const needle = query.trim().toLowerCase();
  if (needle.length === 0) return [...catalogue];

  const matches: CatalogueProvider[] = [];

  for (const provider of catalogue) {
    if (provider.name.toLowerCase().includes(needle) || provider.id.includes(needle)) {
      matches.push(provider);
      continue;
    }

    const models = provider.models.filter(
      (model) =>
        model.name.toLowerCase().includes(needle) || model.id.toLowerCase().includes(needle),
    );

    if (models.length > 0) matches.push({ ...provider, models });
  }

  return matches;
}

/**
 * Where a provider's API lives, for the ones this editor can actually talk to.
 *
 * Everything here speaks the OpenAI wire format at these addresses, which is what lets one
 * client reach all of them. A provider absent from this map can still be used through the
 * custom endpoint - the user supplies the address - and that is the honest arrangement:
 * this is a list of what has been checked, not a claim about what exists.
 */
const BASE_URLS = new Map<string, string>(
  Object.entries({
    openai: "https://api.openai.com/v1",
    openrouter: "https://openrouter.ai/api/v1",
    groq: "https://api.groq.com/openai/v1",
    mistral: "https://api.mistral.ai/v1",
    deepseek: "https://api.deepseek.com/v1",
    xai: "https://api.x.ai/v1",
    together: "https://api.together.xyz/v1",
    "fireworks-ai": "https://api.fireworks.ai/inference/v1",
    cerebras: "https://api.cerebras.ai/v1",
    ollama: "http://127.0.0.1:11434/v1",
  }),
);

export function baseUrlFor(providerId: string): string | null {
  return BASE_URLS.get(providerId) ?? null;
}

/**
 * How this editor talks to a provider.
 *
 * `native` means there is a first-class client for it; `openai-compatible` means it is
 * reached through the OpenAI wire format, which is most of the catalogue; `unsupported`
 * means the user would have to supply an address themselves.
 */
export type Transport = "native" | "openai-compatible" | "unsupported";

export function transportFor(providerId: string): Transport {
  if (providerId === "anthropic" || providerId === "google") return "native";
  return BASE_URLS.has(providerId) ? "openai-compatible" : "unsupported";
}

/*
 * The list a person picks from.
 *
 * models.dev describes everything a provider sells, and most of it cannot hold a
 * conversation with tools: embeddings, speech, image and video generators, realtime audio,
 * moderation filters. Upstream also keeps retired models, and OpenAI sells Pro and Codex
 * models only through its Responses API, which this editor does not speak. Each of those was
 * on the list, and each failed the moment somebody chose it.
 */

/** Ids that name something other than a chat model, whatever else upstream says about them. */
const NOT_A_CHAT_MODEL =
  /(?:^|[-/._])(?:embed|embedding|embeddings|whisper|tts|transcribe|transcription|realtime|moderation|guard|computer-use|lyria|veo|imagen|image|audio|speech)(?:$|[-/._:])/i;

/** OpenAI families sold only through the Responses API. OpenRouter and others translate them. */
const RESPONSES_ONLY = new Set(["gpt-pro", "o-pro", "gpt-codex", "codex"]);

/** Whether ADCode can hold a conversation with this model, tools included. */
export function isUsableModel(providerId: string, model: CatalogueModel): boolean {
  if (!model.toolCall) return false;
  if (model.status === "deprecated") return false;
  if (model.outputs !== undefined && !model.outputs.every((kind) => kind === "text")) return false;
  if (NOT_A_CHAT_MODEL.test(model.id)) return false;
  if (providerId === "openai" && (RESPONSES_ONLY.has(model.family ?? "") || /(?:-pro|codex)(?:$|-)/i.test(model.id))) return false;
  return true;
}

/**
 * Reachable providers and their usable models, newest first.
 *
 * Ollama is left out on purpose: models.dev's Ollama models are a cloud catalogue, while the
 * ones that matter here are whatever this machine has pulled, which the host asks Ollama for.
 */
export function usableCatalogue(providers: readonly CatalogueProvider[]): CatalogueProvider[] {
  const usable: CatalogueProvider[] = [];
  for (const provider of providers) {
    if (provider.id === "ollama" || transportFor(provider.id) === "unsupported") continue;
    const models = provider.models
      .filter((model) => isUsableModel(provider.id, model))
      .sort((a, b) => (b.releaseDate ?? "").localeCompare(a.releaseDate ?? "") || a.name.localeCompare(b.name));
    if (models.length > 0) usable.push({ ...provider, models });
  }
  return usable.sort((a, b) => a.name.localeCompare(b.name));
}

/**
 * The model each provider starts on, best first; the first one the catalogue has wins.
 *
 * Without this a provider started on whatever came first in upstream's order - for
 * OpenRouter a stealth preview few people would choose, which then filled every reply with
 * "I stopped at a limit". The admin catalogue can override it without a release.
 */
export const RECOMMENDED_MODELS: Readonly<Record<string, readonly string[]>> = {
  anthropic: ["claude-sonnet-5-5", "claude-opus-5-5", "claude-sonnet-5", "claude-sonnet-4-6"],
  openai: ["gpt-6.1-sol", "gpt-6-sol", "gpt-5.6", "gpt-5.5"],
  google: ["gemini-flash-latest", "gemini-3.8-flash", "gemini-3.7-flash", "gemini-3.6-flash", "gemini-2.5-flash"],
  openrouter: ["anthropic/claude-sonnet-5.5", "google/gemini-3.8-flash", "openai/gpt-6.1-sol", "anthropic/claude-sonnet-5"],
  groq: ["openai/gpt-oss-120b", "qwen/qwen3.8-27b"],
  xai: ["grok-4.7", "grok-4.6"],
  deepseek: ["deepseek-v4-pro", "deepseek-flash"],
  mistral: ["mistral-medium-latest", "mistral-small-latest"],
  cerebras: ["gpt-oss-120b", "qwen-3.8-27b"],
  "fireworks-ai": ["accounts/fireworks/routers/glm-latest", "accounts/fireworks/models/glm-5p3"],
};

/** The model to start a provider on, or null when the catalogue has none for it. */
export function recommendedModel(
  catalogue: readonly CatalogueProvider[],
  providerId: string,
  preferences: Readonly<Record<string, readonly string[]>> = RECOMMENDED_MODELS,
): string | null {
  const provider = providerIn(catalogue, providerId);
  if (provider === undefined) return null;
  for (const id of preferences[providerId] ?? []) {
    if (provider.models.some((model) => model.id === id)) return id;
  }
  return (provider.models.find((model) => model.toolCall) ?? provider.models[0])?.id ?? null;
}

/** What a request to this model has to respect, or undefined when the catalogue does not know it. */
export function traitsOf(catalogue: readonly CatalogueProvider[], providerId: string, modelId: string): ModelTraits | undefined {
  const model = providerIn(catalogue, providerId)?.models.find((one) => one.id === modelId);
  if (model === undefined) return undefined;
  return { reasoning: model.reasoning, effortLevels: model.effortLevels ?? null, maxOutput: model.maxOutput ?? null };
}
