/**
 * Which models exist, and which of them this machine can reach.
 *
 * The provider list used to be a hardcoded map of four names in the main process, which
 * meant the model dropdown showed models the user's key could not reach and hid ones it
 * could. This replaces it with the published catalogue - and, more importantly, with the
 * idea that the list is *data* rather than a build-time decision.
 *
 * Two sources, in that order:
 *
 * - **The snapshot**, generated by `scripts/catalogue.mjs` and shipped in the binary, so a
 *   first launch with no network has a fully populated connection screen rather than an
 *   empty one that looks broken.
 * - **The live fetch**, which replaces it whenever one succeeds. Never required.
 *
 * This module is pure: parsing and merging only. Fetching and caching belong to the shell.
 */
import { SNAPSHOT_PROVIDERS, SNAPSHOT_TAKEN_ON } from "./catalogueSnapshot.ts";
import type { CatalogueModel, CatalogueProvider } from "./catalogueTypes.ts";

export type { CatalogueModel, CatalogueProvider } from "./catalogueTypes.ts";

export { SNAPSHOT_TAKEN_ON };

/** What ships in the binary. */
export const BUNDLED_CATALOGUE: readonly CatalogueProvider[] = SNAPSHOT_PROVIDERS;

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null;

function modelsFrom(raw: unknown): CatalogueModel[] {
  if (!isRecord(raw)) return [];

  const models: CatalogueModel[] = [];

  for (const entry of Object.values(raw)) {
    if (!isRecord(entry)) continue;

    const id = entry["id"];
    if (typeof id !== "string" || id.length === 0) continue;

    const name = entry["name"];
    models.push({
      id,
      name: typeof name === "string" && name.length > 0 ? name : id,
      toolCall: entry["tool_call"] === true,
      reasoning: entry["reasoning"] === true,
    });
  }

  return models;
}

/**
 * Read the published catalogue into our own shape.
 *
 * Every field is checked. This is arbitrary JSON from the network reaching a list the user
 * will pick from, and the shape upstream publishes is not a promise anybody made us.
 */
export function parseCatalogue(raw: unknown): CatalogueProvider[] {
  if (!isRecord(raw)) return [];

  const providers: CatalogueProvider[] = [];

  for (const [key, entry] of Object.entries(raw)) {
    if (!isRecord(entry)) continue;

    const models = modelsFrom(entry["models"]);
    // A provider with no models is a row that can only disappoint.
    if (models.length === 0) continue;

    const id = entry["id"];
    const name = entry["name"];
    const env = entry["env"];
    const doc = entry["doc"];

    providers.push({
      id: typeof id === "string" && id.length > 0 ? id : key,
      name: typeof name === "string" && name.length > 0 ? name : key,
      env: Array.isArray(env) ? env.filter((one): one is string => typeof one === "string") : [],
      doc: typeof doc === "string" ? doc : null,
      models,
    });
  }

  return providers.sort((a, b) => a.name.localeCompare(b.name));
}

/**
 * The live catalogue where there is one, the snapshot where there is not.
 *
 * A live answer replaces a provider wholesale rather than being merged into it field by
 * field: a model that upstream has removed should disappear, and a merge would keep it
 * forever.
 */
export function mergeCatalogue(
  bundled: readonly CatalogueProvider[],
  live: readonly CatalogueProvider[],
): CatalogueProvider[] {
  if (live.length === 0) return [...bundled];

  const byId = new Map(bundled.map((provider) => [provider.id, provider]));
  for (const provider of live) byId.set(provider.id, provider);

  return [...byId.values()].sort((a, b) => a.name.localeCompare(b.name));
}

export function providerIn(
  catalogue: readonly CatalogueProvider[],
  id: string,
): CatalogueProvider | undefined {
  return catalogue.find((provider) => provider.id === id);
}

/**
 * Providers and models matching a query.
 *
 * Matches the provider's name as well as the model's, because "anthropic" is a perfectly
 * reasonable thing to type when looking for Claude.
 */
export function searchCatalogue(
  catalogue: readonly CatalogueProvider[],
  query: string,
): CatalogueProvider[] {
  const needle = query.trim().toLowerCase();
  if (needle.length === 0) return [...catalogue];

  const matches: CatalogueProvider[] = [];

  for (const provider of catalogue) {
    if (provider.name.toLowerCase().includes(needle) || provider.id.includes(needle)) {
      matches.push(provider);
      continue;
    }

    const models = provider.models.filter(
      (model) =>
        model.name.toLowerCase().includes(needle) || model.id.toLowerCase().includes(needle),
    );

    if (models.length > 0) matches.push({ ...provider, models });
  }

  return matches;
}

/**
 * Where a provider's API lives, for the ones this editor can actually talk to.
 *
 * Everything here speaks the OpenAI wire format at these addresses, which is what lets one
 * client reach all of them. A provider absent from this map can still be used through the
 * custom endpoint - the user supplies the address - and that is the honest arrangement:
 * this is a list of what has been checked, not a claim about what exists.
 */
const BASE_URLS = new Map<string, string>(
  Object.entries({
    openai: "https://api.openai.com/v1",
    openrouter: "https://openrouter.ai/api/v1",
    groq: "https://api.groq.com/openai/v1",
    mistral: "https://api.mistral.ai/v1",
    deepseek: "https://api.deepseek.com/v1",
    xai: "https://api.x.ai/v1",
    together: "https://api.together.xyz/v1",
    "fireworks-ai": "https://api.fireworks.ai/inference/v1",
    cerebras: "https://api.cerebras.ai/v1",
    ollama: "http://127.0.0.1:11434/v1",
  }),
);

export function baseUrlFor(providerId: string): string | null {
  return BASE_URLS.get(providerId) ?? null;
}

/**
 * How this editor talks to a provider.
 *
 * `native` means there is a first-class client for it; `openai-compatible` means it is
 * reached through the OpenAI wire format, which is most of the catalogue; `unsupported`
 * means the user would have to supply an address themselves.
 */
export type Transport = "native" | "openai-compatible" | "unsupported";

export function transportFor(providerId: string): Transport {
  if (providerId === "anthropic" || providerId === "google") return "native";
  return BASE_URLS.has(providerId) ? "openai-compatible" : "unsupported";
}
