/**
 * AI: the assistant, and the memory it shares with every other agent.
 */
import type { HelpEntry } from "../types.ts";

export const AI_ENTRIES: readonly HelpEntry[] = [
  {
    id: "ai.seesYourApp",
    title: "The assistant sees your app",
    plain: "The assistant opens the web app you are building in a browser of its own, looks at any page, clicks and types through it like a visitor, and fixes what it finds.",
    why: "An assistant that only reads code has to guess whether a page works. Looking at it - the words on screen, the errors in the console, the requests that failed, a screenshot - turns \"it should work\" into \"I checked, and it works\", and it catches the broken image or the button that does nothing before you do.",
    how: "Ask in plain words: \"check the contact form sends\", \"look at the pricing page on a phone\", \"open the about page\". Or type /check in the assistant's composer, or run AI: Check My Running App from the command palette, and it looks at the app at desktop and phone width, clicks through the main links and buttons, and fixes what is broken. It starts the live preview by itself when it is not running - a framework's dev server or a plain file server - and waits for its address. The latest screenshot it took appears in the conversation under What the assistant saw, with how many problems it found; click it to open that page in the preview. When it opens a page for you, the preview card in the chat and an open preview window go to that page. Its browser opens only addresses on this computer, forgets everything when it closes, and closes itself after a few idle minutes. A model that cannot read images gets the same report as text.",
    group: "ai",
    settingIds: [],
    related: ["workbench.preview", "ai.agentTools", "ai.composerCommands"],
  },
  {
    id: "ai.agentTools",
    title: "What the assistant can do",
    plain: "Besides reading and changing code, the assistant can delete, move and rename files, keep a dev server running, wait out long installs and builds, and show its plan as a checklist.",
    why: "When it cannot do a job with a proper tool, an assistant improvises with shell commands no Undo can reverse, gives up on anything slower than half a minute, or tells you to run the server yourself. With the right tools it just does the job, and you can put it back.",
    how: "Nothing to set up - ask for what you want. Deleted, moved and renamed files are part of the turn's Undo: the Changed files card under the answer lists them, deletions struck through, and Undo puts every one back, images included. A dev server or watcher runs in the background while the assistant keeps working, reads what it prints and looks at the address it serves; it stops when you close the folder or quit. Commands may run for up to ten minutes and report their real exit code, and Stop ends a command and everything it started. For a bigger job the assistant keeps a Plan card in the conversation, ticking steps off as it goes. Its search shows the lines around each match and finds code as plain text, edits survive a mismatch in indentation, it can look at images in your project, and web pages it reads for documentation come back as clean text. Every tool is listed in plain words on the Tools page under Built-in - run Tools: The Assistant's Built-in Tools. Deleting and moving work when AI edits apply automatically; in review mode the assistant says what to move instead.",
    group: "ai",
    settingIds: [],
    related: ["ai.seesYourApp", "workbench.toolsPage", "adcode.ai.editPolicy"],
  },
  {
    id: "ai.team",
    title: "AI Team",
    plain: "Create named agents with their own instructions and models, then let a team divide a task - messaging each other as they work and sharing the project's memory - and bring its results back for review.",
    why: "Independent research, coding, and checking can finish faster without making one assistant carry every detail in the same context.",
    how: "Open Agents from the Vibe sidebar or the command palette. Create agents under Your agents with a name, look, instructions, connection, model and the tools they may use. Enable Run after teammates for an agent that should receive others' handoffs first. Choose Select for a Team, tick two to four agents, press Set up Team and describe the shared task. The Team appears as one box under Needs you with its members' mascots; press Start to begin. Select the box to see each step it took. Review combined changes before applying them, or Stop a running team. Requests share each connection's rate limit, and Teams count towards Agents working at once. The assistant can also suggest a Team for a big request in the chat.",
    group: "ai",
    settingIds: ["adcode.ai.agentProfiles"],
    related: ["adcode.ai.isolatedWorkspaces", "adcode.ai.taskTokenBudget", "adcode.ai.editPolicy"],
  },
  {
    id: "ai.inlineEdit",
    title: "Edit with AI",
    plain: "Select code, press Ctrl+E and say what to change. The rewrite appears in place, highlighted green under the struck-out original, for you to accept or reject.",
    why: "Small changes should not need a conversation. Adding error handling, renaming across a function or converting a loop happens where you are looking, and nothing reaches disk until you save.",
    how: "In Code mode, select the lines to change - or put the cursor where new code should go - and press Ctrl+E, or right-click and choose ADCode: Edit with AI. Type an instruction such as \"add input validation\" and press Enter. The new code appears highlighted green with the lines it replaced shown struck through above it. Press Ctrl+Enter or Accept to keep it, Esc or Reject to put the original back, or type a follow-up to refine the result. An accepted edit is an ordinary unsaved change: Ctrl+Z undoes it, and it is saved only when you save. It uses the model chosen in Connect a model and sends only the selection and the code around it.",
    group: "ai",
    settingIds: [],
    shortcut: "Ctrl+E",
    related: ["workbench.aiContext", "adcode.ai.inlineCompletion", "ai.connect"],
  },
  {
    id: "ai.composerCommands",
    title: "Slash commands and @ files",
    plain: "Type / in the assistant's composer for ready-made commands like /review and /test, or @ to put any project file in the conversation.",
    why: "Typing is faster than hunting for a button, and each command asks the way an experienced engineer would - including checking its own work - so answers come back verified rather than guessed.",
    how: "Type / at the start of the composer to list every command; keep typing to filter, then press Enter or Tab. /review and /commit attach your uncommitted changes and ask for a review or a commit message. /check asks the assistant to look at your running app in its own browser and fix what is broken. /fix, /test, /plan, /refactor, /explain, /optimize, /security, /docs and /build write a careful prompt that you finish in your own words. /new, /history, /model, /preview, /team and /schedule act at once. Type @ anywhere to search the project's files and add one as a chip; a file open in the editor sends its unsaved text. In an empty composer, the Up arrow brings back your earlier prompts.",
    group: "ai",
    settingIds: [],
    related: ["adcode.ai.chatWidget", "workbench.aiContext", "ai.inlineEdit"],
  },
  {
    id: "adcode.ai.provider",
    title: "Provider",
    plain: "Which company's AI you want to use. You bring your own account and key.",
    why: "Different models are better at different things, and cost different amounts. ADCode does not resell anybody's AI, so the choice - and the bill - is yours.",
    how: "Open Connect a model, pick a provider, and paste your key. ADCode checks the key works before saving it. Keys are kept in your operating system's own password store, never in a settings file. The local option, Ollama, needs no key at all - it talks to a model running on your own machine, and its row says what is true right now: Running with how many models, Installed but not running (with Start Ollama), or Not installed (with Download Ollama).",
    group: "ai",
    settingIds: ["adcode.ai.provider"],
    related: ["ai.connect", "adcode.ai.chatWidget"],
  },
  {
    id: "adcode.ai.model",
    title: "Model",
    plain: "Which particular AI, from that company, answers you.",
    why: "Bigger models are cleverer and slower; smaller ones are quick and cheap. Most people want a big one for hard questions and a small one for everything else.",
    how: "Pick from the list, which shows only models that can work as your assistant - ones that write text and use tools - newest first. Each says what it reads at once and what it costs per million tokens, and is tagged Recommended (the one Use this model picks), New, Free or Free tier where that is true. To switch quickly, click the model chip beside the send button: it lists the model in use, each connected provider's recommended model and the ones you used recently, with More models and providers for the full list. Switching takes effect on your next message - it does not restart the conversation. Thinking effort sets how hard reasoning models think: Auto lets the provider decide, higher efforts answer harder questions better and cost more; each model is sent the nearest level it actually has. A long reply that reaches the model's output limit carries on by itself with more room.",
    group: "ai",
    settingIds: ["adcode.ai.model", "adcode.ai.effort"],
    related: ["adcode.ai.provider", "ai.connect"],
  },
  {
    id: "adcode.ai.chatWidget",
    title: "AI chat workspace",
    plain: "A conversation workspace with searchable history, a live working block per answer, copyable code blocks, per-response actions, a jump-to-latest pill, and an interrupted banner with Edit prompt and Try again.",
    why: "Asking in the editor beats copying code into a browser, because the assistant can already see the project. A playful mascot, a scroll pill that respects your place, and a clear way back from an interrupted turn keep long runs feeling alive instead of hung.",
    how: "Open Assistant from the workbench or command palette. Write in the composer and send your request. The answer reads in the order it happened, as in Claude: a block of work, the text it led to, the next block of work, more text. While a block runs it names the current step with elapsed time — the blue mascot with white eyes bounces while working, its eyes follow your pointer, and clicking it pops a morale-boosting quip. Tool calls stream in as bordered rows, each gaining a checkmark when done. When the assistant starts writing again, that block collapses to Worked for Ns; select its header to expand it again. Scroll up and the transcript stays pinned while a Jump to latest pill appears with a count of new messages; select it to return to the tail. Type a follow-up while the assistant is still working and press Enter: it is queued above the composer and sent by itself when the current turn finishes - Send now stops the current turn and sends it at once, and × drops it. While a turn runs, a line at the bottom of the conversation shows who is working - the assistant's face and name - what it is doing, for how long, and a Stop button. Esc stops it too, and so does the send button, a stop square while a turn runs. If you stop a turn, an interrupted banner offers Edit prompt (your last message back in the composer) and Try again. If a turn fails, a card in the conversation says why in plain words - a rate limit, a request too large for the model, a rejected key, a broken tool call, a network problem - with buttons to try again, switch model, start fresh or report it, and the provider’s exact message under Details. When another model is the fix - out of credit, a rejected key, a model that is gone - choosing one picks the request back up by itself, whether you choose it from the card, the model chip, Connect a model or Settings. A failed turn never breaks the conversation: the next message works as normal. Code arrives in labelled blocks with a Copy button and inline commands read as pills. Every response offers icon actions for Copy, Read aloud, helpful or not helpful, and Retry, with relative time like just now. Use History to browse conversations; Team, schedules and activity opens as a floating panel, and the Agents page shows every agent at work. Share copies the conversation as markdown. When nothing is running, Escape closes the workspace without losing the conversation. A history row's ⋯ menu opens, renames, copies as Markdown or deletes a conversation. The assistant changes existing files with exact replacements instead of rewriting them, reads several files at once, and works through up to 50 steps per request, and Keep going until done carries it on past that by itself. Its edits land in your files as it works, and each turn that changed files gets an Undo card. On an empty conversation, starters get going in one click: Continue picks up the conversation this project was left on, then Explain this project, Build something, Fix an error, Plan new idea and Multitask. With no folder open the starters are things to build - a landing page, a snake game, a to-do app, a portfolio - and asking for something to be built makes a project folder for it. In Vibe a short checklist shows anything still missing: connecting your AI (free in about a minute), then describing what to build.",
    group: "ai",
    settingIds: ["adcode.ai.chatWidget"],
    related: ["ai.sessions", "adcode.ai.inlineCompletion", "adcode.ai.memoryCapture"],
  },
  {
    id: "adcode.ai.inlineCompletion",
    title: "Inline completion",
    plain: "Grey text appears ahead of your cursor guessing the rest of what you are writing. Press Tab to take it.",
    why: "For the lines that are boring and predictable, which is more of them than anybody likes to admit.",
    how: "Off by default. Turn it on and ADCode asks the selected model after you pause, without delaying a keystroke, and cancels the request as soon as the buffer changes. Press Tab to accept grey ghost text, keep typing to ignore it, or press Alt+\\ to request a suggestion yourself. Local keyword and language-server suggestions continue to work separately.",
    group: "ai",
    settingIds: ["adcode.ai.inlineCompletion"],
    shortcut: "Alt+\\",
    related: ["adcode.editing.suggestions", "adcode.ai.provider"],
  },
  {
    id: "adcode.ai.terminalAgentDetection",
    title: "Terminal agent detection",
    plain:
      "If you start an AI tool in ADCode's terminal, ADCode notices and offers to share what it knows about the project with it.",
    why: "So the assistant in your terminal and the one in your editor are working from the same notes instead of two different ideas of the project.",
    how: "On by default. When an agent is recognised, a strip appears above the terminal with the one command that connects it. Nothing is shared unless you press it.",
    group: "ai",
    settingIds: ["adcode.ai.terminalAgentDetection"],
    related: ["adcode.ai.mcpServer", "adcode.ai.memoryCapture"],
  },
  {
    id: "adcode.ai.memoryCapture",
    title: "Memory capture",
    plain:
      "The assistant writes down decisions and conventions about your project, so it does not need telling twice.",
    why: "Explaining the same thing at the start of every conversation is the main reason AI assistants feel forgetful.",
    how: "On by default. Memories are plain markdown files in your project folder. Open Tools and choose Memory to read them grouped by kind, correct or delete one, or add your own; they are also ordinary files you can edit anywhere.",
    group: "ai",
    settingIds: ["adcode.ai.memoryCapture"],
    related: ["adcode.ai.mcpServer", "ai.sessions"],
  },
  {
    id: "ai.terminalTeam",
    title: "Team in the terminal",
    plain:
      "Split one task across several agent CLIs - Claude Code, Codex, Grok, Kimi and the rest - each working in its own terminal pane.",
    why:
      "You already pay for more than one of these, and they are good at different things. Running them one after another wastes the ones that are idle; running them by hand means writing the same briefing four times and watching four panes to see who has finished.",
    how:
      "Right-click a terminal and choose Start a Team here, or run Set Up AI Team. Describe the task, then pick which CLI takes which role. ADCode opens a pane per role, starts that CLI, and briefs it with its own piece, the acceptance criteria, and what its teammates have already finished. A task only starts once everything it depends on has reported done. Each agent is asked to print one line when it finishes; an agent that goes quiet for five minutes is treated as finished instead. Nothing is sandboxed - these are your CLIs editing your working tree, which is why you confirm the plan first. Closing a pane fails just that task and leaves the others running.",
    group: "ai",
    settingIds: [],
    related: ["ai.team", "adcode.ai.terminalAgentDetection", "adcode.ai.autoContinue"],
  },
  {
    id: "ai.liveAgents",
    title: "Live agent view",
    plain:
      "Watch every agent at work in the chat: the code it is writing types in as the model produces it, commands show their output as they run, and agents on a Team pass messages you can see.",
    why:
      "An agent working out of sight is hard to trust and hard to stop in time. Seeing the code appear line by line, and seeing teammates tell each other what they changed, shows you what is happening while there is still time to step in.",
    how:
      "On by default. When the assistant writes a file or runs a command, a live window appears in the conversation: the file's name, the code typing in, then the files it touched and whether it ran checks. When agents from the Agents page, a Team, a race or Team in the terminal are working, a live room sits above the chat with their mascots side by side and a window for each. When one agent messages another, hands off its work, or edits a file a teammate already edited, the sender turns to the receiver and a speech bubble crosses between them; the line under the mascots keeps what was said. Click a mascot or a window's title bar to fill the room with that agent, and Hide windows to keep just the mascots. Every background agent's window has Stop in its title bar (Stop team for a Team, which stops its members together), and the assistant's own turn stops from the line under its window; with two or more runs going, Stop all in the room's header stops them in one go. A reply types in as the agent writes it, and its mascot is marked typing. The ⋯ beside Stop opens the agent's actions: open it on the Agents board, edit the saved agent, or hide the windows. Each window shows Checks passed, Check failed or Unverified, from the commands the agent actually ran - never from what it claims. Turn it off in Settings > AI > Live agent view.",
    group: "ai",
    settingIds: ["adcode.ai.liveAgentView"],
    related: ["ai.team", "ai.terminalTeam", "ai.raceMode"],
  },
  {
    id: "adcode.ai.autoContinue",
    title: "Continue terminal AI after limits",
    plain:
      "A detected terminal assistant can receive a literal “continue” after it says a usage or rate limit has reset.",
    why:
      "Long-running terminal tasks should not need you to watch the clock and return only to type one word.",
    how:
      "Off by default. When enabled, ADCode reads only the terminal output already visible in its own terminal. A clear usage-limit message with an explicit retry delay schedules one continuation. Unknown reset times and changed or ambiguous terminal state stop safely. A repeated limit may schedule the next attempt up to your retry cap. Closing ADCode or turning this setting off cancels every pending continuation.",
    group: "ai",
    settingIds: ["adcode.ai.autoContinue", "adcode.ai.autoContinueRetries"],
    related: ["adcode.ai.terminalAgentDetection", "adcode.ai.mcpServer"],
  },
  {
    id: "adcode.ai.scheduledMessages",
    title: "Scheduled AI messages",
    plain:
      "Write a prompt now and ask a supported AI target to receive it later while ADCode is open.",
    why:
      "A reminder that can actually reach the assistant is useful for follow-up reviews, delayed provider windows, and work you want to queue without leaving an agent running.",
    how:
      "Choose Schedule beside the chat composer, choose where to send the message and set a local time, then confirm. Built-in chat is always available. For a detected terminal AI, first choose Allow next schedule while its prompt is visibly waiting; later terminal activity removes that one-time permission. If ADCode, the project, or scheduled messages are unavailable at delivery time, the message is marked missed and waits for you to choose Run now.",
    group: "ai",
    settingIds: ["adcode.ai.scheduledMessages"],
    related: ["adcode.ai.autoContinue", "adcode.ai.chatWidget", "ai.autoCompact"],
  },
  {
    id: "ai.autoCompact",
    title: "Long chat memory and auto-compact",
    plain:
      "Chats remember: reopen one tomorrow, restart ADCode or switch model, and the assistant carries on where you left off. When a chat gets long, ADCode summarises the older part so it never runs out of room.",
    why:
      "Every model can only read so much at once. Without this, a long chat eventually fails, and a reopened one starts from nothing - so you explain your project again. Compaction keeps the goals, decisions, files and your preferences, and keeps the newest turns word for word.",
    how:
      "On by default. The meter beside the chat's composer shows how full the model's context is (Context 34%, say); hover it for the numbers and when it compacts. At 80% - or 70% or 90%, in Settings - ADCode asks the same model to summarise the older part and the chat shows Earlier conversation compacted with View summary. Compact whenever you like with /compact, or /compact keep the API decisions to say what matters most, or Compact now from the meter or the command palette. Long Agents-board runs compact the same way instead of stopping at the limit. The summary is saved with the conversation, so reopening it from Conversations picks up from the summary and the messages after it.",
    group: "ai",
    settingIds: ["adcode.ai.autoCompact", "adcode.ai.autoCompactAt"],
    related: ["adcode.ai.scheduledMessages", "adcode.ai.chatWidget", "workbench.agentsBoard"],
  },
  {
    id: "adcode.ai.mcpServer",
    title: "MCP server",
    plain:
      "Lets AI tools outside ADCode - Claude Code, Codex, and others - read and write the same project notes.",
    why: "One set of notes shared by every assistant you use, rather than each one starting from nothing.",
    how: "On by default, but it needs Node.js 22.13 or newer installed: your agent starts the server with the Node.js on your computer, not with ADCode. Run node --version in a terminal to check, and install the current LTS from nodejs.org if it is missing or older. Then open Tools and choose Memory: Share with your other AI tools shows the exact command, with a Copy button (Settings shows it too). Run it once, from your project folder. Without Node.js the command is still accepted, but the server fails to start inside your agent.",
    group: "ai",
    settingIds: ["adcode.ai.mcpServer"],
    related: ["adcode.ai.memoryCapture", "adcode.ai.terminalAgentDetection"],
  },
  {
    id: "adcode.ai.customBaseUrl",
    title: "Custom endpoint",
    plain:
      "Point ADCode at any AI service by pasting its address - including one running on your own computer.",
    why: "Most services speak the same format, so one address is all it takes to use a gateway, a cheaper host, or a model you run yourself.",
    how: "Set Provider to Custom, paste the address, and give it your key. The Connect screen checks it works before saving.",
    group: "ai",
    settingIds: ["adcode.ai.customBaseUrl"],
    related: ["ai.connect", "adcode.ai.provider"],
  },
  {
    id: "adcode.ai.isolatedWorkspaces",
    title: "AI file tools",
    plain:
      "The assistant reads, edits and runs commands directly in your open project. What it does lands in your real files as it works, and every turn can be undone.",
    why: "Isolation kept edits safe but made simple work feel missing: proposals sat in a sandbox queue instead of reaching the folder. Direct edits deliver real results the moment the turn finishes.",
    how: "On by default. Ask it to build, fix, create or change files and the result is in your project, with the Explorer refreshing to show it. Reads never change anything. Writes are still guarded: unsaved files pause file edits until you save, so nothing you have not saved gets overwritten, and destructive shell commands stay blocked — run those yourself in the terminal. Chats belong to the open folder only: the chat banner names the folder with its task and chat counts, and Switch opens the folder popup. Turning this off keeps chat available but disables the built-in file tools. Beyond reading, listing, and searching files, the assistant can find files by pattern (for example every image), outline a file's symbols before reading it, delete and move files with Undo, run tests, typechecks and dev servers in the project, look at the running app in its own browser, and fetch documentation pages.",
    group: "ai",
    settingIds: ["adcode.ai.isolatedWorkspaces"],
    related: ["adcode.ai.chatWidget", "adcode.ai.taskTokenBudget"],
  },
  {
    id: "ai.memoryEditor",
    title: "Project memory",
    plain: "Read, correct and add to what the assistant has learned about your project - decisions, conventions and preferences - all in one place.",
    why: "Memory you cannot see is memory you cannot trust. When a note is wrong, fixing it once stops every assistant and agent repeating the mistake.",
    how: "Open Tools and choose Memory, or Tools: Project Memory in the command palette. Notes are grouped into Decisions, Conventions, Preferences and Session notes, each showing who wrote it and when. Edit changes a note, Delete forgets it, and Add memory writes one yourself - give it a short name, a one-line summary and the detail. Changes are searchable by the assistant straight away. Share with your other AI tools gives the command that lets Claude Code, Cursor and others use this same memory.",
    group: "ai",
    settingIds: [],
    related: ["adcode.ai.memoryCapture", "adcode.ai.mcpServer", "workbench.toolsPage"],
  },
  {
    id: "adcode.ai.parallelAgents",
    title: "Agents working at once",
    plain: "How many agents on the Agents board, and Team roles, may work at the same time. The rest wait their turn as Queued.",
    why: "More agents at once finishes a pile of tasks sooner, but spends your key faster and is likelier to run into a provider's rate limit. Three is quick without being greedy.",
    how: "Settings > AI > Agents working at once: pick 1 to 6. A run that is waiting shows Queued on its box and starts on its own, oldest first, as soon as another agent finishes or is stopped. Raising the number starts queued runs straight away. It counts agents in this window; the main chat is never queued.",
    group: "ai",
    settingIds: ["adcode.ai.parallelAgents"],
    related: ["workbench.agentsBoard", "ai.team", "ai.connect"],
  },
  {
    id: "ai.raceMode",
    title: "Race mode",
    plain: "Give the same task to two or three agents at once - different models if you like - then compare their work side by side and keep the best.",
    why: "One model is often almost right. Trying a few and choosing costs a little more and saves the back-and-forth of fixing an almost-right answer.",
    how: "On the Agents page press New task (or run Agents: Race Several Agents on One Task), describe the task, turn on Race and tick two or three agents. Each works in its own copy; its box shows Race 1 of 3 and so on. A race is never applied on its own. When every lane has finished, press Compare on any of them: each lane shows its agent, model, cost, proof of work and what it said. Keep this one applies that lane to your project and discards the others.",
    group: "ai",
    settingIds: [],
    related: ["workbench.agentsBoard", "adcode.ai.parallelAgents", "ai.team"],
  },
  {
    id: "ai.agentMascots",
    title: "Agent mascots",
    plain: "Each saved agent has its own little character - a shape and a colour - and its face shows how that agent's work is going.",
    why: "On a busy board you should not have to read to know what needs you. A worried face with a ! stands out from a sleepy one, and a Reviewer never looks like a Tester.",
    how: "Every agent gets a look of its own from the moment it is created; change it in the agent editor by picking one of eight shapes and ten colours. On the board the face follows the work: thinking while it works, alert with a ! when it needs you, proud when its work is ready to review, happy once it has landed, confused when something went wrong, and sleepy while it waits or after it stops. With Reduce motion on, mascots stay still but still change face. Each card on the Agents board has Run, Edit, Duplicate and Delete; Delete asks first, and runs an agent already did stay on the board. The built-in assistant's own face and name are in Customise chat.",
    group: "ai",
    settingIds: [],
    related: ["workbench.agentsBoard", "ai.team"],
  },
  {
    id: "adcode.ai.editPolicy",
    title: "AI edit approval",
    plain:
      "Choose how the assistant's edits reach your files: it applies them as it works and you can undo any turn (the default), or each turn's changes wait for you to apply them.",
    why:
      "Most of the time you want the result, not a queue of diffs to approve. Applying automatically lets the assistant build, run and fix in one go - the way Cursor's agent does - and one click still takes a whole turn back. Review is there for the times you want to see a change before it lands.",
    how:
      "Switch at any time from the approval menu in the chat's composer (it reads Auto or Review) or in Settings. Apply automatically is the default: files change as the assistant goes, and when a turn changes files the chat shows them with Undo, which puts every file back as it was before that turn and removes files the turn created. If you edited one of those files afterwards, Undo asks before overwriting your change. Undo covers edits made with the assistant's file tools; what a command it ran did to the disk (an install or a build, say) is not recorded. With Review every change, edits are staged in an isolated copy of the project instead; when the turn ends, one card in the conversation shows everything it changed with Apply all changes, Discard and each file's diff, and nothing reaches your files until you apply. Changes in the sidebar lists anything still waiting.",
    group: "ai",
    settingIds: ["adcode.ai.editPolicy"],
    related: ["adcode.ai.keepGoing", "adcode.ai.isolatedWorkspaces", "adcode.ai.scheduledMessages"],
  },
  {
    id: "adcode.ai.keepGoing",
    title: "Keep going until done",
    plain: "When the assistant stops at its step limit in the middle of a long job, it carries on by itself instead of waiting for you to say Continue.",
    why: "Long builds - a whole site, a refactor across many files - can need more than one turn's worth of steps. With this on, you can hand over a big job and come back to it finished.",
    how: "On by default. Turn it off from the approval menu in the chat's composer or in Settings. When a turn ends at the step limit, ADCode sends Continue for you, up to five times in a row, and says so in the conversation each time. Sending your own message or pressing Stop resets the count. With it off, the assistant stops at its step limit and a Continue button picks up where it left off. Together with Apply automatically, and Automations to schedule the job, work runs start to finish without you.",
    group: "ai",
    settingIds: ["adcode.ai.keepGoing"],
    related: ["adcode.ai.editPolicy", "adcode.ai.scheduledMessages", "adcode.ai.chatWidget"],
  },
  {
    id: "adcode.ai.taskTokenBudget",
    title: "Task token budget",
    plain: "Optionally sets a hard ceiling for one assistant task, checked before each new request can spend your key.",
    why: "Long tool loops and repeated context can cost far more than the first question suggests. Checking the whole request before it starts is safer than warning after the tokens are gone.",
    how: "Paused while the assistant edits directly: with no isolated tasks created, there is nothing to cap, so these rows are disabled. Unlimited stays the default. When caps return, choose 25k, 100k, or 250k, or type any number from 1000 to 10000000 into Custom token budget.",
    group: "ai",
    settingIds: ["adcode.ai.taskTokenBudget", "adcode.ai.taskTokenBudgetCustom"],
    related: ["adcode.ai.isolatedWorkspaces", "adcode.ai.provider"],
  },
  {
    id: "ai.workspaceStorage",
    title: "AI workspace storage",
    plain: "Limits how much disk space task copies use and how long finished sandboxes and rollback checkpoints stay.",
    why: "Project copies can be large, but deleting the only safe way back is worse than filling a quota. ADCode treats active work and rollback checkpoints differently for that reason.",
    how: "Terminal sandboxes are cleaned oldest first. An applied task may lose its sandbox when space is tight, but its only rollback checkpoint is kept. If active work leaves no safe room, ADCode refuses the new task and tells you to raise the quota or discard one.",
    group: "ai",
    settingIds: [
      "adcode.ai.sandboxQuota",
      "adcode.ai.sandboxRetention",
      "adcode.ai.checkpointRetention",
    ],
    related: ["adcode.ai.isolatedWorkspaces", "adcode.ai.taskTokenBudget"],
  },
  {
    id: "adcode.ai.designTaste",
    title: "Design taste skill",
    plain: "Before the assistant or an agent builds or restyles a page, screen or game, it reads a design guide so the result does not look like every other AI-made page.",
    why: "Asked for a page, AI models reach for the same purple gradient, centred headline and three equal cards every time. The guide names those habits and what to do instead, so what you get looks designed for your project.",
    how: "On by default. When the work is a user interface, the assistant reads the bundled taste-skill guide (by Leonxlnx, MIT licence) - you will see Reading the design guide in its steps - and follows it while keeping your project's own stack: a plain HTML, CSS and JavaScript project stays plain, and an existing design system wins. It also reads a guide on finishing every file instead of leaving placeholders. Questions that are not about an interface never load it, so they cost nothing extra. Turn it off in Settings > AI > Design taste skill.",
    group: "ai",
    settingIds: ["adcode.ai.designTaste"],
    related: ["adcode.ai.chatWidget", "ai.agentTools"],
  },
  {
    id: "ai.usage",
    title: "AI usage",
    plain: "Shows how many tokens the chat and your agents have used, and roughly what that cost, model by model.",
    why: "You pay your provider for every token. Seeing which model used what - today, this week or this month - tells you where the money goes before the bill does.",
    how: "Select Usage in the chat's header (or ••• when docked), choose Usage by model in the context meter's menu, or run AI: Show Usage. Pick Today, 7 days, 30 days or All time. The top shows total tokens, requests and estimated cost; a bar per day shows when you used it; each model has its share, tokens in and out, requests from the chat and from agents, and a cost from the model catalogue's prices. Counts the provider did not report are estimated and marked ≈; a model with no catalogue price says No price rather than $0. Everything is kept on this machine only, and Clear usage removes it. Your provider's billing page has the exact bill.",
    group: "ai",
    settingIds: [],
    related: ["ai.autoCompact", "adcode.ai.model"],
  },
];
