/**
 * Editing: the writing surface itself.
 *
 * These are the entries people read first, because the editing surface is what they are
 * looking at when they wonder what a setting does.
 */
import type { HelpEntry } from "../types.ts";

export const EDITING_ENTRIES: readonly HelpEntry[] = [
  {
    id: "adcode.editing.bracketPairColorization",
    title: "Bracket pair colorization",
    plain:
      "Brackets get colours. The one that opens and the one that closes are the same colour, so you can see which goes with which.",
    why: "When code is nested several layers deep, finding the bracket that closes the one you are looking at means counting. Colour turns counting into looking.",
    how: "Nothing to do - it is on. Turn it off if you find the colours noisy.",
    group: "editing",
    settingIds: ["adcode.editing.bracketPairColorization"],
    related: ["adcode.editing.indentGuides", "adcode.editing.codeFolding"],
  },
  {
    id: "adcode.editing.inlineErrorLens",
    title: "Inline error and warning lens",
    plain: "When a line has a mistake, the message about it sits right at the end of that line.",
    why: "Otherwise the message lives in a panel at the bottom, or inside a tooltip you have to hover to see. Both mean looking away from the line you are fixing.",
    how: "On by default. The message is dimmed and shortened so it never covers your code, and it hides itself on the line your cursor is on while you type.",
    group: "editing",
    settingIds: ["adcode.editing.inlineErrorLens"],
    related: ["adcode.editing.plainEnglishErrors", "adcode.formatting.lintDiagnostics"],
  },
  {
    id: "adcode.editing.inlineGitBlame",
    title: "Inline git blame",
    plain: "Beside the line your cursor is on, it quietly says who last changed it and when.",
    why: "Reading somebody else's code, the useful question is often not what a line does but why it was written. The commit that added it usually says.",
    how: "Off by default, because it puts text beside your cursor all day. Turn it on and click a line; the note appears at the end of it.",
    group: "editing",
    settingIds: ["adcode.editing.inlineGitBlame"],
    related: ["adcode.git.blame", "adcode.git.fileTimeline"],
  },
  {
    id: "adcode.editing.stickyScroll",
    title: "Sticky scroll",
    plain:
      "As you scroll down inside a long function, its name stays stuck at the top of the editor so you never lose track of where you are.",
    why: "Two hundred lines into a file, the thing you most want to know is which function you are inside. Scrolling back up to check is how you lose your place.",
    how: "On by default. Click a stuck line at the top to jump back to it.",
    group: "editing",
    settingIds: ["adcode.editing.stickyScroll"],
    related: ["adcode.navigation.breadcrumbs", "adcode.navigation.outline"],
  },
  {
    id: "adcode.editing.indentGuides",
    title: "Indent guides",
    plain: "Faint vertical lines show how far in each line is pushed.",
    why: "In languages where indentation decides what belongs to what - Python especially - the lines are the difference between reading the structure and guessing it.",
    how: "On by default. The guide for the block your cursor is in is brighter than the rest.",
    group: "editing",
    settingIds: ["adcode.editing.indentGuides"],
    related: ["adcode.editing.bracketPairColorization"],
  },
  {
    id: "adcode.editing.todoHighlighting",
    title: "TODO and FIXME highlighting",
    plain:
      "Notes you leave yourself in comments - TODO, FIXME, HACK - get a colour so they stand out.",
    why: "A note you cannot find is a note you did not leave. These are the comments you actually want to trip over later.",
    how: "On by default, and only inside real comments - the word TODO in a piece of text or a string is left alone. Edit → List TODOs and FIXMEs collects them from every open file into the Problems panel, and says when there are none.",
    group: "editing",
    settingIds: ["adcode.editing.todoHighlighting"],
    related: ["adcode.editing.inlineErrorLens"],
  },
  {
    id: "adcode.editing.spellCheck",
    title: "Check spelling in comments",
    plain:
      "Misspelled words in comments get a wavy underline, and the fix is one click away on the lightbulb.",
    why: "A typo in a comment is the one kind nothing else catches - the compiler does not read comments, the linter does not read them, and reviewers skim them. So it sits there forever.",
    how: "Off by default. Edit → Check Spelling in Comments runs it over every open file and reports into the Problems panel, including when it finds nothing. It only flags words it can name a correction for, so a library, a product, or somebody's name is left alone instead of underlined - which is why it never becomes the noise you switch off. Code is never checked: an identifier is named, not spelled.",
    group: "editing",
    settingIds: ["adcode.editing.spellCheck"],
    related: ["adcode.editing.todoHighlighting"],
  },
  {
    id: "adcode.editing.commentTones",
    title: "Colour comments by intent",
    plain:
      "Start a comment with !, ?, or * and it takes a colour. Start one with a second // and it fades, because that is code you commented out.",
    why: "A warning, an open question, and a line of dead code are three different kinds of writing that all render the same grey. One character tells them apart.",
    how: "Off by default. Line comments only - a /** block */ begins with * by convention, and colouring those would mark every documented function in a project.",
    group: "editing",
    settingIds: ["adcode.editing.commentTones"],
    related: ["adcode.editing.todoHighlighting"],
  },
  {
    id: "adcode.editing.autoCloseTags",
    title: "Close tags automatically",
    plain:
      "Type the end of an opening tag and the closing one appears by itself. Type a closing bracket and it finishes the tag you still have open.",
    why: "Forgetting to close a tag is the most common way HTML breaks, and the error it produces rarely points at the tag you forgot.",
    how: "On by default in HTML, XML, JSX, and templates. Type >, and the closing tag is written for you with the cursor left between them.",
    group: "editing",
    settingIds: ["adcode.editing.autoCloseTags"],
    related: ["adcode.editing.autoRenamePairedTag"],
  },
  {
    id: "adcode.editing.fileTemplates",
    title: "Start new files from a template",
    plain:
      "A brand new file already has the boring first lines in it - the doctype for a web page, the main function for a C program.",
    why: "Nobody remembers the exact opening lines of every language, and looking them up is the least interesting part of starting something.",
    how: "On by default. Make a new file with a known extension and the boilerplate is there. Press Ctrl+Z once if you would rather start empty.",
    group: "editing",
    settingIds: ["adcode.editing.fileTemplates"],
    related: ["adcode.navigation.fuzzyFileOpen"],
  },
  {
    id: "adcode.editing.autoRenamePairedTag",
    title: "Auto-rename paired tag",
    plain: "Change the name of an opening tag and its closing tag changes to match, by itself.",
    why: "Renaming one and not the other breaks the page, and you usually find out somewhere else entirely.",
    how: "On by default. Edit the name inside an opening tag; the closing tag follows as you type, and one press of Ctrl+Z undoes both together.",
    group: "editing",
    settingIds: ["adcode.editing.autoRenamePairedTag"],
    related: ["adcode.editing.autoCloseTags"],
  },
  {
    id: "adcode.editing.pathAutocomplete",
    title: "Path autocomplete",
    plain:
      "When you are typing the name of another file, it offers you the files that are really there.",
    why: "A mistyped path is a broken import, and the error it causes names the wrong thing surprisingly often. Being offered only files that exist makes the mistake impossible.",
    how: "On by default. Start typing a path inside quotes or an import and the list appears. Type / to go into a folder.",
    group: "editing",
    settingIds: ["adcode.editing.pathAutocomplete"],
    related: ["adcode.editing.suggestions", "adcode.navigation.fuzzyFileOpen"],
  },
  {
    id: "adcode.editing.trailingWhitespace",
    title: "Render trailing whitespace",
    plain: "Extra spaces left hanging at the end of a line are made visible.",
    why: "They are invisible by definition, they show up as changes in every review, and some languages care about them.",
    how: "Off by default, since dots at the end of lines are a distraction if you are not hunting them. Turn it on and they appear as faint marks.",
    group: "editing",
    settingIds: ["adcode.editing.trailingWhitespace"],
    related: ["adcode.formatting.formatOnSave"],
  },
  {
    id: "adcode.editing.minimap",
    title: "Minimap",
    plain: "A tiny picture of the whole file down the right-hand edge, that you can click to jump.",
    why: "You often remember roughly where something was - near the top, in that dense block - without remembering its name. The shape of the file is a real way to navigate.",
    how: "On by default. Drag the highlighted box to scroll, or click anywhere on it to jump there.",
    group: "editing",
    settingIds: ["adcode.editing.minimap"],
    related: ["adcode.navigation.outline"],
  },
  {
    id: "adcode.editing.codeFolding",
    title: "Code folding",
    plain: "Collapse a chunk of code down to one line, and open it again when you want it.",
    why: "A file is easier to read when the parts you are not working on are out of the way.",
    how: "On by default. Click the small arrow in the margin beside a line, or press Ctrl+Shift+[ to fold and Ctrl+Shift+] to unfold.",
    group: "editing",
    settingIds: ["adcode.editing.codeFolding"],
    related: ["adcode.navigation.outline", "adcode.editing.stickyScroll"],
  },
  {
    id: "adcode.editing.multiCursor",
    title: "Multi-cursor",
    plain: "Put more than one cursor on the page and type in all those places at once.",
    why: "Changing the same word in six places is six edits done one at a time, or one edit done six times at once.",
    how: "Ctrl+click to add a cursor anywhere. Ctrl+D adds one at the next copy of the word you have selected. Ctrl+Alt+Up or Down adds one on the line above or below. Escape drops back to one.",
    group: "editing",
    settingIds: ["adcode.editing.multiCursor"],
    shortcut: "CmdOrCtrl+D",
    related: ["adcode.editing.columnSelection", "adcode.navigation.globalSearch"],
  },
  {
    id: "adcode.editing.columnSelection",
    title: "Column selection mode",
    plain:
      "Dragging the mouse selects a rectangle of text - a straight column down the page - instead of following the words.",
    why: "Useful for lining up columns of data or stripping the same prefix off twenty lines.",
    how: "Off by default, because it is a mode: while it is on, every mouse drag makes a box instead of selecting text, and that is not something to switch on by accident. Turn it on when you need it and off again after.",
    group: "editing",
    settingIds: ["adcode.editing.columnSelection"],
    related: ["adcode.editing.multiCursor"],
  },
  {
    id: "adcode.editing.suggestions",
    title: "Suggestions as you type",
    plain: "A little list pops up guessing what you are about to type, so you can pick it instead.",
    why: "It saves typing, and more importantly it saves remembering exact names.",
    how: "On by default. Keep typing to narrow the list, press Tab or Enter to take the highlighted one, Escape to dismiss it.",
    group: "editing",
    settingIds: ["adcode.editing.suggestions"],
    related: ["adcode.editing.wordSuggestions", "adcode.ai.inlineCompletion"],
  },
  {
    id: "adcode.editing.acceptOnEnter",
    title: "Accept suggestion with Enter",
    plain: "With the suggestion list open, pressing Enter takes the suggestion instead of starting a new line.",
    why: "It is what makes suggestions fast. It is also the thing that annoys people who wanted a new line, which is why it is its own switch rather than part of suggestions.",
    how: "On by default. Turn it off and Enter always starts a new line; Tab still takes the suggestion.",
    group: "editing",
    settingIds: ["adcode.editing.acceptOnEnter"],
    related: ["adcode.editing.suggestions"],
  },
  {
    id: "adcode.editing.wordSuggestions",
    title: "Suggest words already in the file",
    plain: "Even with nothing clever available, it will suggest words you have already used nearby.",
    why: "This is the fallback for languages with no language server. A dumb suggestion of a word you definitely typed is still better than typing it again.",
    how: "On by default. It only ever offers words from the file you are in.",
    group: "editing",
    settingIds: ["adcode.editing.wordSuggestions"],
    related: ["adcode.editing.suggestions", "adcode.language.lspClient"],
  },
  {
    id: "adcode.editing.plainEnglishErrors",
    title: "Explain errors in plain English",
    plain: "Confusing error messages get rewritten into a sentence that says what actually went wrong.",
    why: "Compiler messages are written for people who already know the compiler. Most of the time the real meaning is simple and the wording is not.",
    how: "On by default. The rewritten sentence is shown first and the compiler's original wording is always kept underneath, because sometimes the exact words are what you need to search for.",
    group: "editing",
    settingIds: ["adcode.editing.plainEnglishErrors"],
    related: ["adcode.editing.inlineErrorLens", "adcode.formatting.lintDiagnostics"],
  },
];
