/**
 * Structure: how the pieces of a project connect.
 *
 * These are the entries for the switches that control the tree drawing and the two
 * directions of the style-to-markup link.
 */
import type { HelpEntry } from "../types.ts";

export const STRUCTURE_ENTRIES: readonly HelpEntry[] = [
  {
    id: "adcode.structure.projectTreeLines",
    title: "Draw trees with connecting lines",
    plain:
      "Little lines join each file to the folder it lives in, like a family tree, so you can see what is inside what.",
    why: "Without them you have to judge nesting by how far a row is pushed across, which means counting pixels.",
    how: "On by default. Turn it off to get plain indentation instead.",
    group: "structure",
    settingIds: ["adcode.structure.projectTreeLines"],
    related: ["structure.popup", "adcode.navigation.outline"],
  },
  {
    id: "adcode.structure.elementToRules",
    title: "Show the rules that style an element",
    plain: "Click something on the page and see every style rule that changes how it looks.",
    why: "A class is written in one file and used in another, and nothing normally connects the two.",
    how: "On by default. Works in HTML, and in React, Vue, Angular and Handlebars templates.",
    group: "structure",
    settingIds: ["adcode.structure.elementToRules"],
    related: ["adcode.structure.selectorToElements", "structure.cssLinks"],
  },
  {
    id: "adcode.structure.selectorToElements",
    title: "Show the elements a rule styles",
    plain: "Click a style rule and see the things on the page it actually affects.",
    why: "It turns a class name nobody can trace into a list of elements you can click.",
    how: "On by default. Open the Structure popup with a stylesheet in front of you.",
    group: "structure",
    settingIds: ["adcode.structure.selectorToElements"],
    related: ["adcode.structure.elementToRules", "structure.cssLinks"],
  },
  {
    id: "adcode.structure.unusedSelectors",
    title: "Point out rules that style nothing",
    plain: "Tells you when a style rule does not match anything in your project any more.",
    why: "A rule left behind by a deleted component is invisible, and stylesheets only ever grow.",
    how: "Off by default, deliberately. It compares names, so it cannot see a class built at runtime or one generated by a CSS module - on projects that use those it is wrong more often than right. Turn it on and the findings appear in the Problems panel.",
    group: "structure",
    settingIds: ["adcode.structure.unusedSelectors"],
    related: ["adcode.structure.missingClasses", "adcode.formatting.lintDiagnostics"],
  },
  {
    id: "adcode.structure.missingClasses",
    title: "Point out classes nothing defines",
    plain: "Tells you when you have used a class name that no stylesheet actually defines.",
    why: "It is almost always a typo, and a mistyped class is completely silent - the element just renders unstyled, usually on a page nobody has open.",
    how: "On by default. Findings appear in the Problems panel beside everything else.",
    group: "structure",
    settingIds: ["adcode.structure.missingClasses"],
    related: ["adcode.structure.unusedSelectors", "adcode.formatting.lintDiagnostics"],
  },
];
