/**
 * The parts of ADCode with no switch of their own.
 *
 * A feature with no settings row arguably needs explaining more than one with a row, not
 * less - there is nothing to read it off, and no obvious place to look. The command
 * palette, the structure popup, and the earnings ledger are all things people either find
 * by accident or never find at all.
 */
import type { HelpEntry } from "../types.ts";

export const WORKBENCH_ENTRIES: readonly HelpEntry[] = [
  {
    id: "workbench.allFeatures",
    title: "All Features",
    plain: "A searchable library of everything ADCode can do, with an Open button and a plain explanation beside every feature.",
    why: "You should not need to know a command's name, shortcut, or menu before you can discover it.",
    how: "Choose the four-cell All Features button below Earnings, or open View and choose All Features. Search by a feature name or describe what you want to do. Choose Open to use it and ? to understand it.",
    group: "workbench",
    settingIds: [],
    related: ["workbench.universalSearch", "workbench.commandPalette"],
  },
  {
    id: "workbench.universalSearch",
    title: "Universal search",
    plain: "The search box in the title bar finds ADCode features, commands, files, recent folders, and symbols together.",
    why: "One search is faster when you remember what you want but not which menu, panel, or file contains it.",
    how: "Choose the title-bar search and type a name or goal. Use the arrow keys and Enter to open a result. Start with > for commands. Ctrl+P, Ctrl+Shift+P, Ctrl+T, and Ctrl+Shift+F still open their focused searches.",
    group: "workbench",
    settingIds: [],
    related: ["workbench.allFeatures", "workbench.commandPalette", "adcode.navigation.fuzzyFileOpen"],
  },
  {
    id: "workbench.commandPalette",
    title: "Command palette",
    plain: "One box that can run anything ADCode does. Type what you want rather than hunting a menu.",
    why: "There are hundreds of commands and no menu can hold them all. If you can name it, you can run it.",
    how: "Press Ctrl+Shift+P and start typing. The shortcut for each command is shown beside it, so it teaches you the keys as you use it.",
    group: "workbench",
    settingIds: [],
    shortcut: "CmdOrCtrl+Shift+P",
    related: ["workbench.keybindings", "adcode.navigation.fuzzyFileOpen"],
  },
  {
    id: "workbench.keybindings",
    title: "Keyboard shortcuts",
    plain: "Every shortcut can be changed to whatever keys you prefer.",
    why: "Muscle memory from another editor is worth more than any default we could pick.",
    how: "Help, then Keyboard Shortcuts. Search for a command, click its keys, and press the combination you want. Conflicts are pointed out rather than silently taking over.",
    group: "workbench",
    settingIds: [],
    related: ["workbench.commandPalette"],
  },
  {
    id: "structure.popup",
    title: "Structure",
    plain:
      "A window showing what is inside the file you are reading, and what is inside the project, drawn as a tree with lines joining each thing to what it belongs to.",
    why: "The file list tells you what is there. It does not tell you what any of it is. This does - and for a function it also shows what that function calls, and what calls it.",
    how: "Open it from the activity bar or its shortcut. Two tabs: This file, and This project. Click any row to jump to it. For a style rule it shows the elements that rule actually affects, and for an element the rules that style it.",
    group: "workbench",
    settingIds: [],
    related: ["adcode.navigation.outline", "adcode.navigation.goToDefinition", "structure.cssLinks"],
  },
  {
    id: "structure.cssLinks",
    title: "Style and markup links",
    plain:
      "Click a style rule to see the things on the page it changes, or click something on the page to see the rules that style it.",
    why: "A class name written in one file and used in another is the most common untraceable link in a codebase. This traces it, both ways.",
    how: "Works in HTML, JSX className, and Vue, Angular, and Handlebars templates. It can also point out rules that style nothing, and class names nothing defines - both switchable, since on a large project either list can be long.",
    group: "workbench",
    settingIds: [],
    related: ["structure.popup", "adcode.navigation.goToDefinition"],
  },
  {
    id: "workbench.terminal",
    title: "Built-in terminal",
    plain: "A command line inside ADCode, already pointed at your project folder.",
    why: "Most work needs both an editor and a terminal, and switching windows between them adds up.",
    how: "Open it from the panel at the bottom. You can have several at once, and each remembers what it was doing.",
    group: "workbench",
    settingIds: [],
    related: ["adcode.ai.terminalAgentDetection", "workbench.run"],
  },
  {
    id: "workbench.run",
    title: "Run",
    plain: "One button that runs whatever you are working on, working out the right command by itself.",
    why: "Every language and project starts differently, and remembering which is which is pointless work.",
    how: "Press Run. If the tool it needs is not installed, ADCode says which one and where to get it rather than failing with an error you have to decode.",
    group: "workbench",
    settingIds: [],
    related: ["workbench.terminal", "adcode.language.dapClient"],
  },
  {
    id: "workbench.preview",
    title: "Live preview",
    plain: "See a web page you are building beside your code, updating as you type.",
    why: "Saving, switching to a browser, and refreshing is three steps too many when you are adjusting a layout.",
    how: "Open a HTML file and start the preview. It reloads itself when you save.",
    group: "workbench",
    settingIds: [],
    related: ["workbench.run"],
  },
  {
    id: "workbench.collab",
    title: "Live collaboration",
    plain: "Someone else can open the same files at the same time and you both see each other typing.",
    why: "For fixing something together without one of you reading the other's screen over a call.",
    how: "Start a session and share the invitation. It works over your local network - the code does not travel through anybody else's server.",
    group: "workbench",
    settingIds: [],
    related: ["workbench.terminal"],
  },
  {
    id: "account.earnings",
    title: "Earnings",
    plain: "What you have been paid for the sponsored cards you have seen, listed one by one.",
    why: "So the number is something you can check rather than something you are told.",
    how: "Open the earnings view from the title bar. Every row is a real event with the exact amount. The total is worked out by adding the rows up, so it can never disagree with them. Nothing in ADCode can edit or delete a row - a correction is a new row that points at the one it corrects.",
    group: "account",
    settingIds: [],
    related: ["adcode.ads.enabled", "adcode.ads.frequency", "account.signIn"],
  },
  {
    id: "account.signIn",
    title: "Signing in",
    plain: "Signing in keeps your earnings attached to you rather than to this one computer.",
    why: "Without it, your balance lives only on this machine and is lost if the machine is.",
    how: "Use the account button in the title bar. You can sign in with Google, GitHub, or an email address, and anything you already earned anonymously comes with you.",
    group: "account",
    settingIds: [],
    related: ["account.earnings"],
  },
  {
    id: "gestures.multiSelect",
    title: "Selecting and moving files",
    plain: "Files can be renamed, moved, copied and deleted straight from the file list.",
    why: "Leaving the editor to use a file manager for something this ordinary is a break in the work.",
    how: "Right-click any file for the full list. Drag to move, hold Ctrl while dragging to copy, and F2 to rename. Deleting sends to the recycle bin, not to nowhere.",
    group: "gestures",
    settingIds: [],
    shortcut: "F2",
    related: ["adcode.navigation.fuzzyFileOpen"],
  },
  {
    id: "ai.connect",
    title: "Connect a model",
    plain:
      "The screen where you tell ADCode which AI to use and give it your key. It checks the key works before saving it.",
    why: "A key that was pasted wrong should say so immediately, not silently fail the first time you ask a question.",
    how: "Pick a provider from the list, or choose Custom and paste any address that speaks the OpenAI format - that covers most services, including one running on your own machine. Where a provider supports signing in with an account instead of a key, there is a Sign in button. Keys go to your operating system's password store.",
    group: "ai",
    settingIds: [],
    related: ["adcode.ai.provider", "adcode.ai.model", "ai.sessions"],
  },
  {
    id: "ai.sessions",
    title: "Chat history and memory",
    plain:
      "Every conversation is kept, so you can go back to one. A strip at the top shows exactly what the assistant is remembering right now, and a button clears it.",
    why: "Assistants that forget everything are frustrating, and assistants that remember invisibly are worse. Showing what is remembered makes clearing it something you can actually see work.",
    how: "The list beside the chat holds your past conversations - search them, rename them, delete one, or clear them all. Conversations are stored on your own machine, per project, and are never uploaded.",
    group: "ai",
    settingIds: [],
    related: ["adcode.ai.chatWidget", "adcode.ai.memoryCapture", "ai.connect"],
  },
];
