/**
 * The parts of ADCode with no switch of their own.
 *
 * A feature with no settings row arguably needs explaining more than one with a row, not
 * less - there is nothing to read it off, and no obvious place to look. The command
 * palette, the structure popup, and the earnings ledger are all things people either find
 * by accident or never find at all.
 */
import type { HelpEntry } from "../types.ts";

export const WORKBENCH_ENTRIES: readonly HelpEntry[] = [
  {
    id: "workbench.modes",
    title: "Vibe and Code modes",
    plain: "Vibe is the default conversation window. Code opens as a separate IDE window for the same project.",
    why: "Keep planning and editing visible at the same time, with each window sized for its own work.",
    how: "Start in Vibe and choose Open IDE at the bottom of the Vibe sidebar to open or focus the Code window. Use Vibe in the Code toolbar to return to the conversation window. Opening a file, Browse files in the IDE or Search in files from Vibe opens the IDE on exactly that. Both windows follow the same project; Code restores its editor tabs.",
    group: "workbench",
    settingIds: [],
    related: ["workbench.aiContext", "workbench.allFeatures"],
  },
  {
    id: "workbench.aiContext",
    title: "Ask AI about your code",
    plain: "The assistant already sees the file you are on, your cursor, your selection and the editor's errors. Ctrl+L adds a selection to the conversation as a chip.",
    why: "\"Fix this\" and \"what does this function do\" should just work. Ask about unsaved code, prepare a refactor, find issues or write tests without copying between tools.",
    how: "Nothing to switch on: every message carries the file you are looking at, the cursor line, any selected code, your open tabs and the errors and warnings the editor reports, so the assistant knows what \"this\" means. Select code and press Ctrl+L, or right-click and choose ADCode: Add Selection to Chat, to put it in the composer as a chip without sending - then ask your question. With nothing selected, Ctrl+L still selects the line as usual. Right-click for Explain, Refactor, Write Tests and Find Issues, which prepare instructions you edit before sending. In Vibe mode the editor is hidden, so only file names and errors are shared, never a stale selection.",
    group: "workbench",
    settingIds: [],
    shortcut: "Ctrl+L",
    related: ["workbench.modes", "ai.inlineEdit", "ai.composerCommands"],
  },
  {
    id: "workbench.allFeatures",
    title: "All Features",
    plain: "A searchable library of everything ADCode can do, with an Open button and a plain explanation beside every feature.",
    why: "You should not need to know a command's name, shortcut, or menu before you can discover it.",
    how: "Choose the four-cell All Features button below Earnings, or open View and choose All Features. Search by a feature name or describe what you want to do. Choose Open to use it and ? to understand it.",
    group: "workbench",
    settingIds: [],
    related: ["workbench.universalSearch", "workbench.commandPalette"],
  },
  {
    id: "workbench.universalSearch",
    title: "Universal search",
    plain: "The search box in the title bar finds ADCode features, commands, files, recent folders, and symbols together.",
    why: "One search is faster when you remember what you want but not which menu, panel, or file contains it.",
    how: "Choose the title-bar search and type a name or goal. Use the arrow keys and Enter to open a result. Start with > for commands. Ctrl+P, Ctrl+Shift+P, Ctrl+T, and Ctrl+Shift+F still open their focused searches.",
    group: "workbench",
    settingIds: [],
    related: ["workbench.allFeatures", "workbench.commandPalette", "adcode.navigation.fuzzyFileOpen"],
  },
  {
    id: "workbench.commandPalette",
    title: "Command palette",
    plain: "One box that can run anything ADCode does. Type what you want rather than hunting a menu.",
    why: "There are hundreds of commands and no menu can hold them all. If you can name it, you can run it.",
    how: "Press Ctrl+Shift+P and start typing. The shortcut for each command is shown beside it, so it teaches you the keys as you use it.",
    group: "workbench",
    settingIds: [],
    shortcut: "CmdOrCtrl+Shift+P",
    related: ["workbench.keybindings", "adcode.navigation.fuzzyFileOpen"],
  },
  {
    id: "workbench.keybindings",
    title: "Keyboard shortcuts",
    plain: "Every shortcut can be changed to whatever keys you prefer.",
    why: "Keeping the shortcuts you already know makes changing editors much easier.",
    how: "Help, then Keyboard Shortcuts. Search for a command, click its keys, and press the combination you want. Conflicts are pointed out rather than silently taking over.",
    group: "workbench",
    settingIds: [],
    related: ["workbench.commandPalette"],
  },
  {
    id: "structure.popup",
    title: "Structure",
    plain:
      "A window showing what is inside the file you are reading, and what is inside the project, drawn as a tree with lines joining each thing to what it belongs to.",
    why: "The file list tells you what is there. It does not tell you what any of it is. This does - and for a function it also shows what that function calls, and what calls it.",
    how: "Open it from the activity bar or its shortcut. Two tabs: This file, and This project. Click any row to jump to it. For a style rule it shows the elements that rule actually affects, and for an element the rules that style it.",
    group: "workbench",
    settingIds: [],
    related: ["adcode.navigation.outline", "adcode.navigation.goToDefinition", "structure.cssLinks"],
  },
  {
    id: "structure.cssLinks",
    title: "Style and markup links",
    plain:
      "Click a style rule to see the things on the page it changes, or click something on the page to see the rules that style it.",
    why: "A class name written in one file and used in another is the most common untraceable link in a codebase. This traces it, both ways.",
    how: "Works in HTML, JSX className, and Vue, Angular, and Handlebars templates. It can also point out rules that style nothing, and class names nothing defines - both switchable, since on a large project either list can be long.",
    group: "workbench",
    settingIds: [],
    related: ["structure.popup", "adcode.navigation.goToDefinition"],
  },
  {
    id: "workbench.terminal",
    title: "Built-in terminal",
    plain: "A command line inside ADCode, already pointed at your project folder.",
    why: "Most work needs both an editor and a terminal, and switching windows between them adds up.",
    how: "Open it from the panel at the bottom. You can have several at once, and each remembers what it was doing.",
    group: "workbench",
    settingIds: [],
    related: ["adcode.ai.terminalAgentDetection", "workbench.run"],
  },
  {
    id: "workbench.run",
    title: "Run",
    plain: "One button that runs whatever you are working on, working out the right command by itself.",
    why: "Every language and project starts differently, and remembering which is which is pointless work.",
    how: "Press Run. If the tool it needs is not installed, ADCode says which one and where to get it rather than failing with an error you have to decode.",
    group: "workbench",
    settingIds: [],
    related: ["workbench.terminal", "adcode.language.dapClient"],
  },
  {
    id: "workbench.preview",
    title: "Live preview",
    plain: "See a web page you are building beside your code, updating as you type.",
    why: "Saving, switching to a browser, and refreshing is three steps too many when you are adjusting a layout.",
    how: "Open a HTML file and start the preview. It reloads itself when you save. Open device sizes for one-click Phone, Tablet, or Desktop, labelled W and H boxes with minus and plus steppers, or drag the frame's visible edges — the page reshapes in place without reloading, and Fit scales it down so you never scroll to see it. Turn on Inspect, then right-click anything in the preview to see its width, height, padding, margin, and markup; if it grabs an inner piece instead of the card you meant, walk up the breadcrumb to the parent, which flashes in the page as you pick it. Choose List all for every element's spacing at once.",
    group: "workbench",
    settingIds: [],
    related: ["workbench.run"],
  },
  {
    id: "workbench.collab",
    title: "Live collaboration",
    plain: "Someone else can open the same files at the same time and you both see each other typing.",
    why: "For fixing something together without one of you reading the other's screen over a call.",
    how: "Start a session and share the invitation. It works over your local network - the code does not travel through anybody else's server.",
    group: "workbench",
    settingIds: [],
    related: ["workbench.terminal"],
  },
  {
    id: "account.earnings",
    title: "Earnings",
    plain: "What you have been paid for the sponsored cards you have seen, listed one by one.",
    why: "So the number is something you can check rather than something you are told.",
    how: "Open the earnings view from the title bar. Every row is a real event with the exact amount. The total is worked out by adding the rows up, so it can never disagree with them. Nothing in ADCode can edit or delete a row - a correction is a new row that points at the one it corrects.",
    group: "account",
    settingIds: [],
    related: ["adcode.ads.enabled", "adcode.ads.frequency", "account.signIn"],
  },
  {
    id: "account.signIn",
    title: "Signing in",
    plain: "Signing in keeps your earnings attached to you rather than to this one computer.",
    why: "Without it, your balance lives only on this machine and is lost if the machine is.",
    how: "Use the account button in the title bar. You can sign in with Google, GitHub, or an email address, and anything you already earned anonymously comes with you.",
    group: "account",
    settingIds: [],
    related: ["account.earnings"],
  },
  {
    id: "gestures.multiSelect",
    title: "Selecting and moving files",
    plain: "Files can be renamed, moved, copied and deleted straight from the file list.",
    why: "Leaving the editor to use a file manager for something this ordinary is a break in the work.",
    how: "Right-click any file for the full list. Drag to move, hold Ctrl while dragging to copy, and F2 to rename. Deleting sends to the recycle bin, not to nowhere. Use Split editor right in a file header or the command palette to edit two files side by side. Each panel has a file picker; selecting a tab or opening a file uses the focused panel. Drag the divider to resize, or focus it and use arrow keys. Merge editor panels returns to the focused file without closing your buffers.",
    group: "gestures",
    settingIds: [],
    shortcut: "F2",
    related: ["adcode.navigation.fuzzyFileOpen"],
  },
  {
    id: "workbench.imagePreview",
    title: "Image preview",
    plain: "Click an image file and it shows as a picture instead of text.",
    why: "Opening a PNG as text shows garbage characters. A picture is what you actually want to check.",
    how: "Click any png, jpg, gif, webp, svg, ico, or bmp file in the Explorer. It previews in the editor area with its file size and dimensions. Images cannot be edited here - they are preview-only. Use File > Open Image Preview or the command palette to pick one directly.",
    group: "workbench",
    settingIds: [],
    related: ["gestures.multiSelect", "adcode.navigation.fuzzyFileOpen"],
  },
  {
    id: "ai.connect",
    title: "Connect a model",
    plain:
      "Connect an AI provider in three steps - choose a provider, check and save its key, pick a model - or save several named API connections with a requests-per-minute limit, including NVIDIA NIM.",
    why: "A key that was pasted wrong should say so immediately, not silently fail the first time you ask a question.",
    how: "Open Connect a model and follow the three steps at the top. Choose a provider or add a named connection with an OpenAI-compatible base URL and exact model ID. The NVIDIA NIM preset fills its hosted endpoint. Set requests per minute, save the connection, then check and save its API key. When nothing is connected, the Assistant shows a banner that works directly with your codebase and opens Connect. Select the connection for chat or an agent. Chat, completion, and team requests share its queue. Server cooldowns are respected; token or account quotas can still cause rate-limit errors. Keys remain encrypted by the operating system.",
    group: "ai",
    settingIds: ["adcode.ai.connections"],
    related: ["adcode.ai.provider", "adcode.ai.model", "ai.sessions", "ai.team"],
  },
  {
    id: "ai.sessions",
    title: "Chat history and memory",
    plain:
      "Every conversation is kept in Today, Yesterday, and older groups, so you can go back to one. A strip at the top shows exactly what the assistant is remembering right now, and a button clears it.",
    why: "Assistants that forget everything are frustrating, and assistants that remember invisibly are worse. Showing what is remembered makes clearing it something you can actually see work.",
    how: "Press Ctrl+Shift+N or choose New conversation to start fresh; the current one is kept. In Vibe, past conversations are listed in the sidebar, grouped into Today, Yesterday and older; in the IDE, choose History from the conversation's actions menu. Search them by title or by anything said in them, rename them, or delete one. The header shows the current conversation name and Share copies it as markdown. Conversations are stored on your own machine, per project, and are never uploaded.",
    group: "ai",
    settingIds: [],
    related: ["adcode.ai.chatWidget", "adcode.ai.memoryCapture", "ai.connect"],
  },
  {
    id: "workbench.openIde",
    title: "Open IDE in a separate window",
    plain: "Keep the Vibe-first launcher where it is and open the full editor-first IDE beside it, on the same project.",
    why: "Planning and building want different screen shapes. Two windows means the conversation stays visible while the editor, terminal and preview get a whole window of their own.",
    how: "Choose Open IDE at the bottom of the Vibe sidebar, or in the top bar when the window is narrow. ADCode opens one editor-first IDE window and focuses it on later clicks. The Vibe window stays open; use Vibe in the IDE toolbar to return to it.",
    group: "workbench",
    settingIds: [],
    related: ["workbench.modes", "workbench.vibeSidebar", "workbench.allFeatures"],
  },
  {
    id: "workbench.debugLog",
    title: "Report a problem with a debug log",
    plain: "When something goes wrong, ADCode records what failed - the assistant, a window, or the app itself - in a debug log you can send with a report.",
    why: "\"The AI stopped working\" is hard to fix from a description. The log says which part failed, with the exact error, the version and the model you had selected, so a problem can be fixed from one report instead of a back-and-forth.",
    how: "Choose Help > Report a Problem, describe what happened, and keep Include debug log ticked; select See exactly what is included to read the attached text first. When the assistant fails, the error card's Report problem button opens the same form, already filled in. To send the full log another way, choose Help > Copy Debug Log and paste it, or Help > Save Debug Log to save it as a text file. The log keeps recent errors, which tool failed, and turn timings. It never holds your API keys, prompts, answers, file contents, file paths or project names - those are removed before anything is written - and nothing is sent unless you send it.",
    group: "workbench",
    settingIds: [],
    related: ["adcode.ai.chatWidget", "workbench.allFeatures"],
  },
  {
    id: "workbench.vibeSidebar",
    title: "Vibe sidebar",
    plain: "The left side of the Vibe window: start a conversation, switch project, and see at a glance what has changed.",
    why: "Vibe hides the editor, so something has to tell you that an agent is still working or what has changed. The Changes badge says so without opening anything, and every everyday workflow has a row of its own instead of hiding in a menu.",
    how: "New conversation (Ctrl+Shift+N) starts fresh; earlier ones stay under Conversations, grouped by day and searchable. The project card shows the folder, its branch and how many files have changed - select it to switch to a recent project, open or clone one, or see the project overview. Changes opens the Changes panel beside the conversation (select it again to close it); its badge counts the files you have not committed, and turns blue when something needs you, such as a conflict or - if you chose Review every change - AI edits waiting to apply. Preview shows the running app, Automations schedules messages, and Agents & tools manages saved agents, MCP tools and skills. The footer holds Open IDE, notifications, your earnings, Settings and More for everything else. Drag the sidebar's right edge to resize it. Press Ctrl+B to hide or show it; on a narrow window it becomes a drawer that the menu button or Ctrl+B opens.",
    group: "workbench",
    settingIds: [],
    shortcut: "Ctrl+B",
    related: ["workbench.modes", "workbench.openIde", "workbench.changes", "ai.sessions"],
  },
  {
    id: "workbench.changes",
    title: "Changes panel",
    plain: "Every file that changed since your last commit - what the assistant did and what you did - with its line counts, its diff one click away, and one button to commit and push it all.",
    why: "When the assistant edits as it works, this is where you see what it touched and save the result. It reads like Cursor's changes view, but you never have to learn staging: every file is included until you untick it, and if you leave the commit message empty ADCode writes one from the files.",
    how: "Choose Changes in the Vibe sidebar, or Show Workspace Changes in the command palette. The bar at the top shows the uncommitted +added −removed total, the branch and Commit & Push; the line under it always says which files the next commit takes. Each row is a file with its line counts, a New or Deleted tag, a revert arrow and a checkbox. Select a file to see its diff - a new file shows its whole contents. Untick a file to leave it out of the next commit; while every box is ticked, Commit & Push takes every file. Commit & Push commits and pushes in one step, with a message such as Update css/app.css and 2 more files when you have not written one; the arrow beside it offers Commit only and Write the commit message. A project not yet connected to GitHub is committed on this computer, and the panel says how to connect it. The revert arrow asks first, then puts an edited file back as it was at the last commit, or moves a new file to the Recycle Bin. The branch button switches branch; the ⋯ button holds Include everything, Pull, Push, Revert all changes and Source Control. In a folder without Git, Turn on version control starts tracking it. On a drive that does not record who owns files (FAT32 or exFAT, most USB sticks), Git refuses a repository until the folder is trusted: one ADCode just created is trusted for you, and for any other the panel says Git needs your OK and offers Trust this folder - trust only folders you made or got from someone you trust, because a repository can run its own scripts. Work from Review mode or an AI Team that is waiting to be applied appears at the top of the panel.",
    group: "workbench",
    settingIds: [],
    related: ["workbench.vibeSidebar", "adcode.git.stageCommitUi", "adcode.ai.editPolicy"],
  },
];
