/**
 * Regenerate the bundled model catalogue.
 *
 * `models.dev` publishes what every provider offers - over two hundred providers and about
 * five megabytes of it. Fetching that at runtime is the right thing to do and cannot be the
 * *only* thing: the connection screen has to be usable on a first launch with no network,
 * and a model list that is empty until a request succeeds looks broken rather than offline.
 *
 * So a trimmed snapshot ships with the app and the live fetch upgrades it. This regenerates
 * the snapshot; run it when the shipped list has aged:
 *
 *     node scripts/catalogue.mjs
 *
 * The snapshot is cut by the same rules the app applies to the live list - `parseCatalogue`
 * and `usableCatalogue`, imported from the source rather than copied, so the two can never
 * disagree about which models a person may pick. That means: providers ADCode can address,
 * and of their models only those that write text, call tools, are not retired and do not
 * need an API this editor does not speak - every one of them, newest first.
 *
 * Written as TypeScript rather than JSON so that importing it needs no `resolveJsonModule`
 * and every bundler here treats it as ordinary source.
 */
import { writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseCatalogue, usableCatalogue } from "../packages/ai/src/catalogue.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const TARGET = resolve(HERE, "..", "packages", "ai", "src", "catalogueSnapshot.ts");

async function main() {
  const response = await fetch("https://models.dev/api.json", {
    headers: { "user-agent": "adcode-catalogue-snapshot" },
  });

  if (!response.ok) {
    process.stderr.write(`models.dev answered ${String(response.status)}\n`);
    process.exit(1);
  }

  const providers = usableCatalogue(parseCatalogue(await response.json()));
  if (providers.length === 0) {
    process.stderr.write("models.dev answered, but nothing in it is usable - the snapshot was left alone\n");
    process.exit(1);
  }

  const takenOn = new Date().toISOString().slice(0, 10);
  const source = `/**
 * The model catalogue, as it stood when this file was generated.
 * Generated by scripts/catalogue.mjs from models.dev; do not edit by hand.
 */
import type { CatalogueProvider } from "./catalogueTypes.ts";

export const SNAPSHOT_TAKEN_ON = ${JSON.stringify(takenOn)};

export const SNAPSHOT_PROVIDERS: readonly CatalogueProvider[] = ${JSON.stringify(providers, null, 2)};
`;

  await writeFile(TARGET, source, "utf8");

  const models = providers.reduce((total, provider) => total + provider.models.length, 0);
  process.stdout.write(
    `catalogue: ${String(providers.length)} providers, ${String(models)} models -> ${join("packages", "ai", "src", "catalogueSnapshot.ts")}\n`,
  );
  for (const provider of providers) process.stdout.write(`  ${provider.id}: ${String(provider.models.length)}\n`);
}

await main();
