/**
 * Regenerate the bundled model catalogue.
 *
 * `models.dev` publishes what every provider offers - 194 providers and about four
 * megabytes of it. Fetching that at runtime is the right thing to do and cannot be the
 * *only* thing: the connection screen has to be usable on a first launch with no network,
 * and a model list that is empty until a request succeeds looks broken rather than offline.
 *
 * So a trimmed snapshot ships with the app and the live fetch upgrades it. This regenerates
 * the snapshot; run it when the shipped list has aged:
 *
 *     node scripts/catalogue.mjs
 *
 * Trimmed hard on purpose. Only the providers most people reach for, and only the fields
 * the connection screen and the agent actually read - which turns four megabytes into a
 * file that is reasonable to commit and to parse on every launch.
 *
 * Written as TypeScript rather than JSON so that importing it needs no `resolveJsonModule`
 * and every bundler here treats it as ordinary source.
 */
import { writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const TARGET = resolve(HERE, "..", "packages", "ai", "src", "catalogueSnapshot.ts");

/**
 * The providers worth shipping offline.
 *
 * Everything else is one network request away. This list is "what somebody is likely to
 * connect on their first evening", not a judgement about the rest.
 */
const KEEP = [
  "anthropic",
  "openai",
  "google",
  "ollama",
  "openrouter",
  "groq",
  "mistral",
  "deepseek",
  "xai",
  "together",
  "fireworks-ai",
  "cerebras",
  "azure",
  "amazon-bedrock",
  "github-copilot",
];

/** Models per provider, newest first as the source orders them. */
const MAX_MODELS = 40;

const priceMicros = (value) => {
  if (typeof value !== "number" || !Number.isFinite(value) || value < 0) return null;
  const micros = Math.round(value * 1_000_000);
  return Number.isSafeInteger(micros) ? micros : null;
};

async function main() {
  const response = await fetch("https://models.dev/api.json", {
    headers: { "user-agent": "adcode-catalogue-snapshot" },
  });

  if (!response.ok) {
    process.stderr.write(`models.dev answered ${String(response.status)}\n`);
    process.exit(1);
  }

  const all = await response.json();
  const providers = [];

  for (const id of KEEP) {
    const source = all[id];
    if (source === undefined) continue;

    const models = Object.values(source.models ?? {})
      .slice(0, MAX_MODELS)
      .map((model) => {
        const cost = model.cost ?? {};
        return {
          id: model.id,
          name: model.name ?? model.id,
          // The capabilities decide what a role may use; optional prices make automatic
          // routing cost-aware without pretending missing catalogue data is free.
          toolCall: model.tool_call === true,
          reasoning: model.reasoning === true,
          inputCostMicrosPerMillion: priceMicros(cost.input),
          outputCostMicrosPerMillion: priceMicros(cost.output),
          cacheReadCostMicrosPerMillion: priceMicros(cost.cache_read),
          cacheWriteCostMicrosPerMillion: priceMicros(cost.cache_write),
        };
      });

    if (models.length === 0) continue;

    providers.push({
      id: source.id ?? id,
      name: source.name ?? id,
      env: Array.isArray(source.env) ? source.env : [],
      doc: typeof source.doc === "string" ? source.doc : null,
      models,
    });
  }

  const takenOn = new Date().toISOString().slice(0, 10);
  const source = `/**
 * The model catalogue, as it stood when this file was generated.
 * Generated by scripts/catalogue.mjs from models.dev; do not edit by hand.
 */
import type { CatalogueProvider } from "./catalogueTypes.ts";

export const SNAPSHOT_TAKEN_ON = ${JSON.stringify(takenOn)};

export const SNAPSHOT_PROVIDERS: readonly CatalogueProvider[] = ${JSON.stringify(providers, null, 2)};
`;

  await writeFile(TARGET, source, "utf8");

  const models = providers.reduce((total, provider) => total + provider.models.length, 0);
  process.stdout.write(
    `catalogue: ${String(providers.length)} providers, ${String(models)} models -> ${join("packages", "ai", "src", "catalogueSnapshot.ts")}\n`,
  );
}

await main();
