import { describe, expect, it } from "vitest";
import { createAiWorkspaceTask, createFileChange } from "@adcode/ai";
import { parseAiWorkspaceApply, validAiWorkspaceTaskId } from "../src/main/aiWorkspaceIpcValidation.ts";
import { toAiWorkspaceChangeViews, toAiWorkspaceTaskView } from "../src/main/aiWorkspaceViews.ts";
import { CHANNELS } from "../src/shared/api.ts";

it("uses distinct channels for every task command and notification", () => {
  const channels = [
    CHANNELS.aiWorkspaceList,
    CHANNELS.aiWorkspaceCurrent,
    CHANNELS.aiWorkspaceChanges,
    CHANNELS.aiWorkspaceTraces,
    CHANNELS.aiWorkspaceApply,
    CHANNELS.aiWorkspaceDiscard,
    CHANNELS.aiWorkspaceRollback,
    CHANNELS.aiWorkspaceChanged,
  ];
  expect(new Set(channels).size).toBe(channels.length);
});

describe("renderer-safe AI workspace views", () => {
  it("never exposes absolute human or sandbox paths", () => {
    const task = {
      ...createAiWorkspaceTask({
        id: "task-contract",
        workspaceId: "workspace-contract",
        workspaceRoot: "C:/private/project",
        prompt: "Fix it",
        now: 1,
      }),
      sandbox: { kind: "shadow-copy", id: "private-sandbox-id", createdAt: 1 } as const,
      changes: [createFileChange("src/file.ts", "before", "after")],
    };

    const encoded = JSON.stringify(toAiWorkspaceTaskView(task));
    expect(encoded).not.toContain("C:/private/project");
    expect(encoded).not.toContain("private-sandbox-id");
    expect(encoded).toContain("src/file.ts");
  });

  it("turns changes into review hunks without file contents outside those hunks", () => {
    const task = {
      ...createAiWorkspaceTask({
        id: "task-contract",
        workspaceId: "workspace-contract",
        workspaceRoot: "C:/private/project",
        prompt: "Fix it",
        now: 1,
      }),
      changes: [createFileChange("src/file.ts", "before\n", "after\n")],
    };

    expect(toAiWorkspaceChangeViews(task)).toEqual([
      {
        path: "src/file.ts",
        hunks: [{ id: "h0", startLine: 0, original: ["before"], replacement: ["after"] }],
      },
    ]);
  });
});

describe("AI workspace IPC validation", () => {
  it("accepts bounded relative hunk selections", () => {
    expect(
      parseAiWorkspaceApply([{ path: "src/file.ts", acceptedHunkIds: ["h0", "h2"] }]),
    ).toEqual([{ path: "src/file.ts", acceptedHunkIds: ["h0", "h2"] }]);
  });

  it("rejects traversal, absolute paths, duplicate files, invented hunk shapes, and huge input", () => {
    expect(parseAiWorkspaceApply([{ path: "../secret", acceptedHunkIds: ["h0"] }])).toBeNull();
    expect(parseAiWorkspaceApply([{ path: "C:\\secret", acceptedHunkIds: ["h0"] }])).toBeNull();
    expect(
      parseAiWorkspaceApply([
        { path: "same.ts", acceptedHunkIds: ["h0"] },
        { path: "same.ts", acceptedHunkIds: ["h1"] },
      ]),
    ).toBeNull();
    expect(parseAiWorkspaceApply([{ path: "file.ts", acceptedHunkIds: ["../../x"] }])).toBeNull();
    expect(
      parseAiWorkspaceApply(
        Array.from({ length: 201 }, (_, index) => ({ path: `${index}.ts`, acceptedHunkIds: ["h0"] })),
      ),
    ).toBeNull();
  });

  it("accepts only task ids generated by the task domain", () => {
    expect(validAiWorkspaceTaskId("task-abc123")).toBe(true);
    expect(validAiWorkspaceTaskId("../task-abc123")).toBe(false);
    expect(validAiWorkspaceTaskId("x")).toBe(false);
  });
});
