/**
 * Words that are always wrong, and what they were meant to be.
 *
 * **Why a list of misspellings rather than a dictionary.** The obvious way to build a spell
 * checker is to hold a dictionary and flag every word missing from it. Do that to source
 * code and the first thing anybody sees is every product name, every abbreviation, every
 * library, every colleague's surname and every identifier underlined at once - and the
 * thing people do about that is turn the feature off, permanently, before it has ever
 * caught a real typo. The dictionary would have to be large enough to know `kubelet` and
 * `oauth` and `Dayyan`, and no dictionary is.
 *
 * Inverting it removes the problem by construction. A word is flagged only when there is a
 * specific correction to offer, so an unknown word is silence rather than noise, and every
 * report comes with the fix already written. It catches less than a dictionary would; what
 * it catches, it is right about, which is the property that decides whether a checker stays
 * switched on.
 *
 * **What may go in.** Only unambiguous misspellings of English words. Deliberately absent:
 * - British spellings, which are not errors: `initialise`, `colour`, `cancelled`.
 * - Names that are misspelled on purpose and must stay that way. The HTTP `Referer` header
 *   is the famous one; "correcting" it would break the header it names.
 * - Words whose "misspelling" is a real word elsewhere: `dependant` is a person in British
 *   English, so it is left alone rather than risk being wrong about prose.
 */

/** Keyed in lowercase; lookup lowercases first, and capitalisation is restored after. */
export const CORRECTIONS: Readonly<Record<string, string>> = {
  accomodate: "accommodate",
  acheive: "achieve",
  acknowlege: "acknowledge",
  adress: "address",
  aggresive: "aggressive",
  alredy: "already",
  alwasy: "always",
  appearence: "appearance",
  arguement: "argument",
  assignement: "assignment",
  asynchronus: "asynchronous",
  attribte: "attribute",
  authentification: "authentication",
  availabe: "available",
  avaliable: "available",
  becuase: "because",
  begining: "beginning",
  beleive: "believe",
  calender: "calendar",
  catagory: "category",
  charater: "character",
  comitted: "committed",
  commited: "committed",
  comparision: "comparison",
  compatability: "compatibility",
  completly: "completely",
  concatination: "concatenation",
  conected: "connected",
  consistant: "consistent",
  continous: "continuous",
  controll: "control",
  convertion: "conversion",
  coordiante: "coordinate",
  currenty: "currently",
  defalut: "default",
  defintion: "definition",
  defualt: "default",
  delimeter: "delimiter",
  dependancy: "dependency",
  depricated: "deprecated",
  descripton: "description",
  desription: "description",
  diffrent: "different",
  dimention: "dimension",
  dissapear: "disappear",
  effeciency: "efficiency",
  efficent: "efficient",
  enviroment: "environment",
  envrionment: "environment",
  equivalant: "equivalent",
  excpetion: "exception",
  excute: "execute",
  existance: "existence",
  explicitely: "explicitly",
  extention: "extension",
  familar: "familiar",
  fetaure: "feature",
  finaly: "finally",
  foward: "forward",
  fucntion: "function",
  fuction: "function",
  funtion: "function",
  guarentee: "guarantee",
  happend: "happened",
  heirarchy: "hierarchy",
  higlight: "highlight",
  idenifier: "identifier",
  identifer: "identifier",
  immediatly: "immediately",
  implemenation: "implementation",
  implmentation: "implementation",
  inconsistant: "inconsistent",
  independant: "independent",
  indeces: "indices",
  infinit: "infinite",
  inheritence: "inheritance",
  inisde: "inside",
  initalize: "initialize",
  initilize: "initialize",
  instanciate: "instantiate",
  interupt: "interrupt",
  intialize: "initialize",
  invokation: "invocation",
  knowlege: "knowledge",
  langauge: "language",
  lenght: "length",
  libary: "library",
  liek: "like",
  lisence: "license",
  machien: "machine",
  maintainance: "maintenance",
  maintenence: "maintenance",
  managment: "management",
  mesage: "message",
  messsage: "message",
  mispelled: "misspelled",
  neccessary: "necessary",
  necesary: "necessary",
  negociate: "negotiate",
  noticable: "noticeable",
  occassion: "occasion",
  occured: "occurred",
  occurence: "occurrence",
  occurrance: "occurrence",
  ommitted: "omitted",
  opperation: "operation",
  orginal: "original",
  overriden: "overridden",
  paramater: "parameter",
  parametre: "parameter",
  paramter: "parameter",
  particuarly: "particularly",
  perfomance: "performance",
  performace: "performance",
  permanant: "permanent",
  persistant: "persistent",
  posible: "possible",
  postion: "position",
  prefered: "preferred",
  previosly: "previously",
  primative: "primitive",
  priviledge: "privilege",
  probaly: "probably",
  procesing: "processing",
  propery: "property",
  propertly: "properly",
  propogate: "propagate",
  protocal: "protocol",
  pyhton: "python",
  queary: "query",
  recieve: "receive",
  recieved: "received",
  recomend: "recommend",
  recuring: "recurring",
  refered: "referred",
  refernce: "reference",
  refrence: "reference",
  releated: "related",
  relevent: "relevant",
  reponse: "response",
  represenation: "representation",
  reqest: "request",
  requst: "request",
  resonse: "response",
  responce: "response",
  retreive: "retrieve",
  retrive: "retrieve",
  reuqest: "request",
  runing: "running",
  sepcific: "specific",
  seperate: "separate",
  seperator: "separator",
  sequenece: "sequence",
  shoudl: "should",
  similiar: "similar",
  simpliest: "simplest",
  singelton: "singleton",
  specifiy: "specify",
  speficic: "specific",
  statment: "statement",
  strenght: "strength",
  succesful: "successful",
  succesfully: "successfully",
  successfull: "successful",
  sucess: "success",
  sucessful: "successful",
  sufficent: "sufficient",
  supress: "suppress",
  surpress: "suppress",
  syncronous: "synchronous",
  sytem: "system",
  targetting: "targeting",
  teh: "the",
  temlate: "template",
  tempalte: "template",
  temperture: "temperature",
  threshhold: "threshold",
  tolerence: "tolerance",
  tommorow: "tomorrow",
  transation: "transaction",
  transfered: "transferred",
  truely: "truly",
  unecessary: "unnecessary",
  unforseen: "unforeseen",
  unkown: "unknown",
  untill: "until",
  usefull: "useful",
  usualy: "usually",
  vairable: "variable",
  varaible: "variable",
  variabel: "variable",
  verison: "version",
  versoin: "version",
  visibile: "visible",
  wether: "whether",
  widht: "width",
  writting: "writing",
  yeild: "yield",
};
